secrets:
    AUTH0_TEST_USERNAME: ENC[AES256_GCM,data:lPddHbDVfWxaEW7ujLDnWdhIBMFj2hcp,iv:oG3Ebn8ym7g/Z7L3A3BTHRHIk+zzblZKvzMKYMPSfWI=,tag:wV7xJWbnLrj/UWj0fGGQCw==,type:str]
    AUTH0_TEST_PASSWORD: ENC[AES256_GCM,data:3tgQjqv5ktdnnGUQw5Lpuw==,iv:F8zYxqk5P0tV1Pvt6QBlho8H0wuX+K91pgwLzF+4kC8=,tag:HJ4s14d/u2KyP780wFDk/w==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:HevA8uFKCOPF8W/FRjSo/pyUFN66eXwvAxaqT5LdnT0=,iv:qpWNjsRSZ28lWQJGfMoGQvLY8KRKWv1dhR07vCgIvIU=,tag:x5BS26iacdBMv2ZkdCdr3A==,type:str]
    AUTH0_DOMAIN: ENC[AES256_GCM,data:2vv9ay+hC1kN46MG8E0v1Z3G7Dm0hMmLx1/AWg==,iv:9thZflFQ1yhf0jH3u6Om7RV7Y/qYzrTf82hoYrDvyG0=,tag:BUNuHJobt/NoR5FFQBIbIQ==,type:str]
sops:
    age:
        - recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWODlXSGtNSC9pZk16L1o4
            ZW53cXlDYVNqZTNLcG1DQnU3dnFPcnc4eEdzCitJSUh0RFhPc1F0Q2ZzbjFJdmw5
            SDZmVHYyY0JadXlOTWhaeHdpUkNxRTgKLS0tIGxSVk13bmVLeW9aeVhGTWorM090
            QVhacnJWU2dQTVh1OEFvKzYrdUNtMUUK5nzUZOVdg9RIzzB11UknB6piaBmFQ/7r
            TlpFCeN9G/Att1n906Xf1iJP3ckAKB4NgY+FM2rUOJXyIR20+tdZew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T09:52:57Z"
    mac: ENC[AES256_GCM,data:4qmhG/liKJdnEBxvvnxnpb9xJpS8GGjCAHGUVM4dGtYY5+TkfgnSQyvVdg88Ag16nMDTBEeRJO6VfOYD/Wx/PfIYnajhxRm3ZYuPPSJ5t0LGqRryUtR9vJTtHuTew5gjX8FCTvjiGJzqcfTiq11HhN3Xyu7VNwwan50QUvz5oKY=,iv:Rc0/1kH74ahBkNygwFrOZymWMnPj3VCQZ7wBi1d7Rzc=,tag:Cgdjhlc24S2gklSKYe5mPw==,type:str]
    pgp:
        - created_at: "2025-09-26T09:22:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNryRZ+XfAgsSAQdAnymnO6kZh3k7w4twG80/hZRgDCibFdemTCXrIIZ5MV4w
            Ot+03R3axI7eA4T6gjGjnSJbBI1kBLUp2ThTbxN9I7OdvL+kkKw7im5oyK/ltavg
            1GYBCQIQ7C4PUvGyp7x6KbFndUVEgvrFY2sDcLd2OU+Y1aL7TBcGylhSTKDl0xqf
            RO1ZNtq9/MIsDh8HM8e1nqw3sm9DDsv8wvU0xwqmm1oiPLrxu4g4MeP3bPTmdiU2
            MzFP32F2CWA=
            =ORDS
            -----END PGP MESSAGE-----
          fp: 4F8E31286D7997C9625C6F7B322C6F63F594CE7C
        - created_at: "2025-09-26T09:22:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdAe4OTGea67+inl1TZNCOiCb9myl467+6Lh1W2/aSUcAow
            RnT5ZMym8aZEa760y+fBNvxJKjQaMAmRzNt8yRPQHwS+MvF6C3Jq4Osemxof9JYl
            0lwBW/DKi8RnmKgyygtoK4iwTBJELNd1tt6VHn5Q2oNbYy8VBcPGvQZbYZhZduNn
            82KkaMqfrlgCh1vxcgmcAfNB9RAETQZuo46UlYZ1vMaWEambBKTMy6eQd67JnQ==
            =8/3B
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2025-09-26T09:22:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqqdQLSUqHusSAQdAS1YS7z0jmCESufNnhlKLiDOtDkJXST3V4+8d+aK7WEcw
            83sWETB+M6YtlJkcQyRoUJFyuoUq0r4ND8ijz/u50bEN478TmCROxZ5tgmM7kiCJ
            1GYBCQIQ8wuS49J1AvY94FALr1D0dwWyC9ExIWi3cfMROwtEXXkbZKoM9TNYceZF
            P6ZOpeOJ/ANGHrVtIBPwO93Lhco9NCVA1uDGhhgmtCqGklSbtvT9QJdoSbRC/weJ
            6F+MS6zfHNE=
            =+kXR
            -----END PGP MESSAGE-----
          fp: 77D901DDCB59376D9E4131279BAC0E08F5067BB8
        - created_at: "2025-09-26T09:22:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdA9iaHK2+w33a3151vzJWFSD9bjqoVts8/KGWjHCb4EQ4w
            wK6FMGi3YJmRmlBGVvaWAGFOVrrAgNVGX4nHSdJAawLEXLgd+YDLszmpSpEvnbW6
            1GYBCQIQoGX3nT0Cvq2YTjaAyji/UV95ILCGB9c/iyhN2q2jZ+t+YR0VDciXIwhx
            YP2PQt3hNeXESQs7n89KdBr5cvdfmjeVlJgFIQiXJWQOz8xtQ1baajyYzvkPQyFW
            6u/bT8iTp3E=
            =4yGd
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
        - created_at: "2025-09-26T09:22:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DO29iviZqVTMSAQdA7Ab0TIHqhJl9zLIuwV03Wj8UEz0FWoLX17mO3owDAR0w
            TmQBsRcB6FJ55Kt5pqrnKhUUvw4TBmXtLdMsqmabJIyadkCz2AVr27g+HZHjCq+m
            1GYBCQIQiGrJBC5g1CQk8Rb4AHTTGd84OsCZbN9qqtNcxLhs3/WuE8Vh447hlZTv
            yqcjd8mT4Yz3on+Y0dewuppmOnE83/l0EyUAOJAYELQb9EJgVq2EG7Nn9VAHL3Eu
            4PEtHdkNw40=
            =ph4L
            -----END PGP MESSAGE-----
          fp: 484DF208A16D4E209D686E9D65558E016966977A
    unencrypted_suffix: _unencrypted
    version: 3.8.1
