secrets:
    AUTH0_TEST_USERNAME: ENC[AES256_GCM,data:lPddHbDVfWxaEW7ujLDnWdhIBMFj2hcp,iv:oG3Ebn8ym7g/Z7L3A3BTHRHIk+zzblZKvzMKYMPSfWI=,tag:wV7xJWbnLrj/UWj0fGGQCw==,type:str]
    AUTH0_TEST_PASSWORD: ENC[AES256_GCM,data:3tgQjqv5ktdnnGUQw5Lpuw==,iv:F8zYxqk5P0tV1Pvt6QBlho8H0wuX+K91pgwLzF+4kC8=,tag:HJ4s14d/u2KyP780wFDk/w==,type:str]
    AUTH0_CLIENT_ID: ENC[AES256_GCM,data:HevA8uFKCOPF8W/FRjSo/pyUFN66eXwvAxaqT5LdnT0=,iv:qpWNjsRSZ28lWQJGfMoGQvLY8KRKWv1dhR07vCgIvIU=,tag:x5BS26iacdBMv2ZkdCdr3A==,type:str]
    AUTH0_DOMAIN: ENC[AES256_GCM,data:2vv9ay+hC1kN46MG8E0v1Z3G7Dm0hMmLx1/AWg==,iv:9thZflFQ1yhf0jH3u6Om7RV7Y/qYzrTf82hoYrDvyG0=,tag:BUNuHJobt/NoR5FFQBIbIQ==,type:str]
    CHROMATIC_PROJECT_TOKEN: ENC[AES256_GCM,data:VJ3yKBbNB4pvOOZf2lW0vTq8AnU=,iv:/CGREI+uWZRYhRci49MT4LbeLc4PeX1zVbgBFssgf9I=,tag:1fRu1a81ni4niRkjzqpqUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cGJuUHVaL0tNa1ovOFZo
            TDJwaVJKckYzTjdCVVV4MndzQ29tNjVNNURrCnFOYVIwWUJaL0NISjMxY2VCMGlv
            b0VHS1lLa1NpdDNBY3ZwNmRmL2lVOFEKLS0tIFlxS0ZpYllGeTVkb2VkWEIva3Bl
            WlR5NEFtNUpOYTVCcnRzWFo3b0c1Vk0Ku339r6WeqlmYo+JQRim+1/tcbjdwNOkU
            jC2kZtoM9b+m+CpZAp2NVDWOvYv1YycZr78PDELncsTqDkGgQaW21A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
    lastmodified: "2025-09-26T12:20:26Z"
    mac: ENC[AES256_GCM,data:47t79C7AX1bXRMQUDxmOxLpkedoudfXej976eE+n5sM2SQjz/9DzjEkZWWs1mtXj+ZV2kHVRKNNRAEcJdjm4aj1F8cdOwNaFQMaANKwFb8vMIAq6EvUO39mKKa5r272dDT5gkpvENbrk51Lkds0tEKplVd8GTW0VYu/9qrhPU3s=,iv:4xEinkTPSZCij8r4W07MUOnHwZXGA3zIQIgRibhWHs0=,tag:WQgQ4ySdWExucXhHHcooWQ==,type:str]
    pgp:
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DNryRZ+XfAgsSAQdA1oBKVZ43NT4zISSAxwY7OkMW9Jv3zI6mLrQQh2jNuRow
            sn7ybGc8SFydtfSuNtOZEYlBGXbHenZMwR/pv7TGVzoWYgIM/PEZSZNVd12RrY0o
            1GYBCQIQsBjgBwMAHSXN/qT4q0DSW0kDBZCZ3tuBN7mUmDD6F4muu97Vk7uPiwyk
            L9pzpl3Z5t5kuEeVcNtknMzT6cHMXhZ7LEoulYV6KbxAgrwck7RSNMBCp/9dQtI8
            KEyElyvrD7k=
            =uIkC
            -----END PGP MESSAGE-----
          fp: 4F8E31286D7997C9625C6F7B322C6F63F594CE7C
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdA0jAsIuPTjqrizDmqum/ZLhAiw36vaG35Fc8zGjL5pTAw
            t6rFElTogiCQA3JD3UwXCOlQcYZ8NMRT3Gytxy72RpJtMbksJ/ysImyacT+0y/hc
            0lwBjnfq3c8cLH45JEinzBKLIHUenWw8Us1KEA71rZSsx6NDEfQaTJzHTzfpMC1Z
            Vmpez4SVqY8l2C4hOWTN6Y+hhqbi1aqU9m9EmMpAXoBIRP0URfyTajhBZkourQ==
            =yPNt
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DqqdQLSUqHusSAQdAKBc32+tIbm95qrKWoWChhbEx9R6O4UsixzdkqoMLLx0w
            mI2NQ/8x/+v5vBL42HHJMmFeWDGGiuBGfGZBAWEMGkX8KWHvkViiM7jm65tQ17tF
            1GYBCQIQTHAl4VvVrHjg9S27aYD18BUVHqN2OMpDD4OXJObDy/lBfFwF0EPi4T1a
            QyjYRSn1T9K75x6OkrchS490JoTgXOb53g3q/fcCAhuvha4RjTBztrzW7291KG2J
            pejX06sc2nk=
            =ACSA
            -----END PGP MESSAGE-----
          fp: 77D901DDCB59376D9E4131279BAC0E08F5067BB8
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DRbry8yWl6IgSAQdAoIq7UJbf9Db9915VCO3G+wEP76pUGQd8oVIKv2R0eGgw
            Aa96owKdf36CyuF5yfRmZqtBCM35lcc3IQLXTma/1GyzF/tiwhe4eoN+xjCrGElI
            1GYBCQIQiL8TwrrH09aOXtYGRqMUGlwXkGARAphj9i0HoY70gkwV6gDpJv1FXG89
            iK/oEnP9xTr8UN3tsyutlQXC8uoDMDaUbU1mSmyH7hN2xw/VUftY18EjuI5CIDBd
            l4naaU9QAIM=
            =PZSV
            -----END PGP MESSAGE-----
          fp: 11177A43C6E3752E682AC690DBD13117B0A14E93
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DO29iviZqVTMSAQdAfZl2WfiJSlFXm12vr98A74ZgvNI75oRg0Haq7LlCT3Iw
            s+FAy2vJAib9IVAbBrGWtW2StjJtd4l5dzj0jAN3yKx3LQWle1LLzI2bk13KWfAe
            1GYBCQIQ229NyooyBnBXiF65Yo644pm2RA8Y9awIiLxh8oeubXaxB9P8tJRt72M6
            G/69q0r2mKtg36Kwvovh5N10MrknupGRjc9QEeRqm3w5+Poj/JGbSWeT/DM1z2pI
            q4ntXNFR7U8=
            =58WK
            -----END PGP MESSAGE-----
          fp: 484DF208A16D4E209D686E9D65558E016966977A
        - created_at: "2026-06-17T10:01:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWCal0yrIpBwSAQdA88eO5Cab5lUmOQVYeQ1VlnLYwNIJVyigevQuMJaMXRww
            3JoaMVtpZlt/rPwfvWA7DyFB3ZTBvyhJCHyjRwcqbKtVf8Bd4pW2hGNrNr+SiDS9
            1GYBCQIQa852nRQuW2DTWeLyTf2NFBGsKVpjopMWaA7C+wAk14ue/G7ekKKG86ax
            jnM3mUaFUyjF10d5H4tb45b1wbadzIycnteNRA+B89KRqFIBZ36zrWYDcBgmrGMk
            GTXj0qae1wc=
            =JCqy
            -----END PGP MESSAGE-----
          fp: C76B256FCB26806F8AA10A82372F271E3AD80BFC
    unencrypted_suffix: _unencrypted
    version: 3.10.2
