// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type ContainerImageSpec = {
  ref?: string
}

export type ContainerRunAsSpec = {
  uid?: number
  gid?: number
}

export type ContainerMountSpec = {
  kind?: string
  volumeID?: string
  source?: string
  destination?: string
  size?: number
  options?: string[]
}

export type ContainerSecuritySpec = {
  privileged?: boolean
  capabilitiesAdd?: string[]
  capabilitiesDrop?: string[]
}

export type ContainerNetworkSpec = {
  hostNetwork?: boolean
}

export type ContainerResourcesSpec = {
  memoryLimit?: number
  cpuLimit?: number
}

export type ContainerDependsOnSpec = {
  paths?: string[]
  networks?: string[]
  time?: boolean
  containers?: string[]
}

export type ContainerSpecSpec = {
  image?: ContainerImageSpec
  entrypoint?: string[]
  args?: string[]
  workingDir?: string
  runAs?: ContainerRunAsSpec
  environment?: string[]
  mounts?: ContainerMountSpec[]
  security?: ContainerSecuritySpec
  network?: ContainerNetworkSpec
  resources?: ContainerResourcesSpec
  dependsOn?: ContainerDependsOnSpec
}
