// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type MemoryModuleSpec = {
  sizeMiB?: number
  deviceLocator?: string
  bankLocator?: string
  speed?: number
  manufacturer?: string
  serialNumber?: string
  assetTag?: string
  productName?: string
}

export type PCIDriverRebindConfigSpec = {
  pciID?: string
  targetDriver?: string
}

export type PCIDriverRebindStatusSpec = {
  pciID?: string
  targetDriver?: string
}

export type PCIDeviceSpec = {
  class?: string
  subclass?: string
  vendor?: string
  product?: string
  class_id?: string
  subclass_id?: string
  vendor_id?: string
  product_id?: string
  driver?: string
}

export type ProcessorSpec = {
  socket?: string
  manufacturer?: string
  productName?: string
  maxSpeedMhz?: number
  bootSpeedMhz?: number
  status?: number
  serialNumber?: string
  assetTag?: string
  partNumber?: string
  coreCount?: number
  coreEnabled?: number
  threadCount?: number
}

export type SystemInformationSpec = {
  manufacturer?: string
  productName?: string
  version?: string
  serialnumber?: string
  uuid?: string
  wakeUpType?: string
  skuNumber?: string
}
