// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type ConfigSpec = {
  enabled?: boolean
  allowedAPIRoles?: string[]
  allowedKubernetesNamespaces?: string[]
}
