// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/

export type APIServiceConfigSpec = {
  listenAddress?: string
  nodeRoutingDisabled?: boolean
  readonlyRoleMode?: boolean
  skipVerifyingClientCert?: boolean
}

export type BootIDSpec = {
  bootID?: string
}

export type BootedEntrySpec = {
  bootedEntry?: string
}

export type DevicesStatusSpec = {
  ready?: boolean
}

export type DiagnosticSpec = {
  message?: string
  details?: string[]
}

export type EnvironmentSpec = {
  variables?: string[]
}

export type EventSinkConfigSpec = {
  endpoint?: string
}

export type ExtensionServiceConfigFile = {
  content?: string
  mountPath?: string
}

export type ExtensionServiceConfigSpec = {
  files?: ExtensionServiceConfigFile[]
  environment?: string[]
}

export type ExtensionServiceConfigStatusSpec = {
  specVersion?: string
}

export type ImageFactorySchematicSpec = {
  schematicId?: string
  flavor?: string
  apiUrl?: string
}

export type KernelCmdlineSpec = {
  cmdline?: string
}

export type KernelModuleSpecSpec = {
  string?: string
  parameters?: string[]
}

export type KernelModuleStatusSpec = {
  type?: string
  size?: number
  referenceCount?: number
  dependencies?: string[]
  state?: string
  address?: string
}

export type KernelParamSpecSpec = {
  value?: string
  ignoreErrors?: boolean
}

export type KernelParamStatusSpec = {
  current?: string
  default?: string
  unsupported?: boolean
}

export type KmsgLogConfigSpec = {
  destinations?: string[]
}

export type LoadedKernelModuleSpec = {
  size?: number
  referenceCount?: number
  dependencies?: string[]
  state?: string
  address?: string
}

export type UnmetCondition = {
  name?: string
  reason?: string
}

export type MachineStatusStatus = {
  ready?: boolean
  unmetConditions?: UnmetCondition[]
}

export type MachineStatusSpec = {
  stage?: string
  status?: MachineStatusStatus
}

export type MaintenanceServiceConfigSpec = {
  listenAddress?: string
  reachableAddresses?: string[]
}

export type MetaKeySpec = {
  value?: string
}

export type MetaLoadedSpec = {
  done?: boolean
}

export type MountStatusSpec = {
  source?: string
  target?: string
  filesystemType?: string
  options?: string[]
  encrypted?: boolean
  encryptionProviders?: string[]
}

export type OOMActionSpec = {
  triggerContext?: string
  score?: number
  processes?: string[]
}

export type PlatformMetadataSpec = {
  platform?: string
  hostname?: string
  region?: string
  zone?: string
  instanceType?: string
  instanceId?: string
  providerId?: string
  spot?: boolean
  internalDNS?: string
  externalDNS?: string
  tags?: {[key: string]: string}
}

export type SBOMItemSpec = {
  name?: string
  version?: string
  license?: string
  cpes?: string[]
  purls?: string[]
  extension?: boolean
}

export type SecurityStateSpec = {
  secureBoot?: boolean
  ukiSigningKeyFingerprint?: string
  pcrSigningKeyFingerprint?: string
  selinuxState?: string
  fipsState?: string
  bootedWithUKI?: boolean
  moduleSignatureEnforced?: boolean
}

export type ServicePIDSpec = {
  pid?: number
  mountNamespace?: string
}

export type UnattendedInstallStatusSpec = {
  image?: string
  phase?: string
  error?: string
}

export type UniqueMachineTokenSpec = {
  token?: string
}

export type VersionSpec = {
  name?: string
  version?: string
}

export type WatchdogTimerConfigSpec = {
  device?: string
  timeout?: string
}

export type WatchdogTimerStatusSpec = {
  device?: string
  timeout?: string
  feedInterval?: string
}
