// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/
import type { PEMEncodedCertificate, PEMEncodedCertificateAndKey, PEMEncodedKey } from '../common/common.pb'


export type APICertsSpec = {
  acceptedCAs?: PEMEncodedCertificate[]
  client?: PEMEncodedCertificateAndKey
  server?: PEMEncodedCertificateAndKey
  skipVerifyingClientCert?: boolean
}

export type CertSANSpec = {
  ips?: string[]
  dnsNames?: string[]
  fqdn?: string
}

export type EncryptionSaltSpec = {
  diskSalt?: string
}

export type EtcdCertsSpec = {
  etcd?: PEMEncodedCertificateAndKey
  etcdPeer?: PEMEncodedCertificateAndKey
  etcdAdmin?: PEMEncodedCertificateAndKey
  etcdAPIServer?: PEMEncodedCertificateAndKey
}

export type EtcdRootSpec = {
  etcdCA?: PEMEncodedCertificateAndKey
}

export type KubeletSpec = {
  endpoint?: string
  endpointTLSServerName?: string
  acceptedCAs?: PEMEncodedCertificate[]
  bootstrapTokenID?: string
  bootstrapTokenSecret?: string
}

export type KubernetesCertsSpec = {
  schedulerKubeconfig?: string
  controllerManagerKubeconfig?: string
  localhostAdminKubeconfig?: string
  adminKubeconfig?: string
}

export type KubernetesDynamicCertsSpec = {
  apiServer?: PEMEncodedCertificateAndKey
  apiServerKubeletClient?: PEMEncodedCertificateAndKey
  frontProxy?: PEMEncodedCertificateAndKey
}

export type KubernetesRootSpec = {
  name?: string
  endpoint?: string
  local_endpoint?: string
  certSANs?: string[]
  apiServerIPs?: string[]
  dnsDomain?: string
  issuingCA?: PEMEncodedCertificateAndKey
  acceptedCAs?: PEMEncodedCertificate[]
  aggregatorCA?: PEMEncodedCertificateAndKey
  acceptedAggregatorCAs?: PEMEncodedCertificate[]
  serviceAccount?: PEMEncodedKey
  serviceAccountAcceptedKeys?: PEMEncodedKey[]
  issuerURL?: string
  acceptedIssuers?: string[]
  apiAudiences?: string[]
  aesCBCEncryptionSecret?: string
  bootstrapTokenID?: string
  bootstrapTokenSecret?: string
  secretboxEncryptionSecret?: string
  etcdEncryptionConfig?: {[key: string]: unknown}
}

export type MaintenanceRootSpec = {
  ca?: PEMEncodedCertificateAndKey
}

export type OSRootSpec = {
  issuingCA?: PEMEncodedCertificateAndKey
  acceptedCAs?: PEMEncodedCertificate[]
  certSANIPs?: string[]
  certSANDNSNames?: string[]
  token?: string
}

export type TrustdCertsSpec = {
  acceptedCAs?: PEMEncodedCertificate[]
  server?: PEMEncodedCertificateAndKey
}
