// Copyright (c) 2026 Sidero Labs, Inc.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.

//go:build sidero.tools

// talostsgen emits TypeScript interfaces for Talos COSI resource specs.
//
// It discovers all structs tagged with //gotagsrewrite:gen in the Talos machinery
// resources packages, reads their yaml struct tags (the source of truth for the
// wire format), and emits one TypeScript file per package.
//
// Usage:
//
//	go run -tags=sidero.tools github.com/siderolabs/omni/internal/internal/tools/talostsgen [output-dir]
//
// output-dir defaults to frontend/src/api/talos.
package main

import (
	"context"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const resourcesPrefix = "github.com/siderolabs/talos/pkg/machinery/resources/"

// goTypeToScalar maps fully-qualified Go types (pkgPath.TypeName) to a fixed
// TypeScript scalar. Used for types that don't carry TextMarshaler but still
// serialize to a predictable primitive in YAML.
//
// time.Time already implements TextMarshaler so it is caught by hasMarshalText.
var goTypeToScalar = map[string]string{
	// go.yaml.in/yaml/v4 serializes time.Duration via its String() method → "30s".
	"time.Duration": "string",
	// url.URL serializes as its string form.
	"net/url.URL": "string",
	// Talos helpers that wrap bytes/strings.
	"github.com/siderolabs/talos/pkg/machinery/yamlutils.StringBytes":             "string",
	"github.com/siderolabs/talos/pkg/machinery/config/types/v1alpha1.Base64Bytes": "string",
	// atomic.Int64 appears in a few specs but isn't really serialisable; treat as number.
	"sync/atomic.Int64": "number",
}

// goPackageToTSImport maps Go package paths to the TypeScript file that already
// contains equivalent type definitions (generated by the proto pipeline or
// another generator).
var goPackageToTSImport = map[string]string{
	// PEMEncoded* types are defined in common.proto → common.pb.ts.
	"github.com/siderolabs/crypto/x509": "../common/common.pb",
}

const (
	resourcesPattern = "github.com/siderolabs/talos/pkg/machinery/resources/..."
	genMarker        = "gotagsrewrite:gen"
	fileHeader       = `// This file is auto-generated by internal/internal/tools/talostsgen. DO NOT EDIT.
//
// Source of truth: yaml struct tags on the Go types in
// github.com/siderolabs/talos/pkg/machinery/resources/
`
)

func main() {
	ctx := context.Background()

	outDir := "frontend/src/api/talos"
	if len(os.Args) > 1 {
		outDir = os.Args[1]
	}

	// NeedTypes triggers root github.com/siderolabs/talos module checksum lookup.
	// GONOSUMDB=* skips the sum database. Outside workspace mode (e.g. Docker)
	// -mod=mod lets go write the missing hash to go.sum from the local cache.
	// In workspace mode go.work.sum already covers the hash and -mod=mod would
	// be rejected, so we only set it when no workspace is active.
	env := append(os.Environ(), "GONOSUMDB=*")
	if !inWorkspaceMode(ctx) {
		env = append(env, "GOFLAGS=-mod=mod")
	}

	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo,
		Env: env,
	}

	pkgs, err := packages.Load(cfg, resourcesPattern)
	if err != nil {
		fatalf("load packages: %v", err)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	if err = os.MkdirAll(outDir, 0o755); err != nil {
		fatalf("mkdir %s: %v", outDir, err)
	}

	for _, pkg := range pkgs {
		generate(pkg, outDir)
	}
}

// generate emits a TypeScript file for one Go package.
func generate(pkg *packages.Package, outDir string) {
	structs := findTaggedStructs(pkg)
	if len(structs) == 0 {
		return
	}

	g := &gen{
		pkg:     pkg,
		emitted: make(map[string]bool),
		imports: make(map[string]map[string]bool),
		output:  &strings.Builder{},
	}

	for _, s := range structs {
		g.emitStruct(s)
	}

	if g.output.Len() == 0 {
		return
	}

	pkgName := pkg.Name
	path := filepath.Join(outDir, pkgName+".pb.ts")

	var sb strings.Builder
	sb.WriteString(fileHeader)

	// Emit import statements sorted for determinism.
	if len(g.imports) > 0 {
		importPaths := make([]string, 0, len(g.imports))
		for p := range g.imports {
			importPaths = append(importPaths, p)
		}

		sort.Strings(importPaths)

		for _, tsPath := range importPaths {
			names := make([]string, 0, len(g.imports[tsPath]))
			for n := range g.imports[tsPath] {
				names = append(names, n)
			}

			sort.Strings(names)
			fmt.Fprintf(&sb, "import type { %s } from '%s'\n", strings.Join(names, ", "), tsPath)
		}

		sb.WriteByte('\n')
	}

	sb.WriteString(g.output.String())

	if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
		fatalf("write %s: %v", path, err)
	}
}

// structDef holds what we need to emit a TypeScript type.
type structDef struct {
	astStruct *ast.StructType
	typesObj  *types.Struct
	name      string
}

// findTaggedStructs returns all structs in the package that carry //gotagsrewrite:gen.
func findTaggedStructs(pkg *packages.Package) []structDef {
	var result []structDef

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			if !hasGenMarker(genDecl.Doc) {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				astStruct, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				obj := pkg.Types.Scope().Lookup(typeSpec.Name.Name)
				if obj == nil {
					continue
				}

				typesStruct, ok := obj.Type().Underlying().(*types.Struct)
				if !ok {
					continue
				}

				result = append(result, structDef{
					name:      typeSpec.Name.Name,
					astStruct: astStruct,
					typesObj:  typesStruct,
				})
			}
		}
	}

	return result
}

// hasGenMarker reports whether the comment group contains //gotagsrewrite:gen.
func hasGenMarker(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}

	for _, c := range doc.List {
		if strings.Contains(c.Text, genMarker) {
			return true
		}
	}

	return false
}

// gen holds per-package generation state.
type gen struct {
	pkg     *packages.Package
	emitted map[string]bool            // struct names already emitted
	imports map[string]map[string]bool // tsImportPath → set of type names
	output  *strings.Builder
}

// emitStruct writes one TypeScript type to the output, skipping it if it has
// any interface-typed field (e.g. DeviceConfigSpecSpec.Device) or no yaml-tagged
// fields at all.
func (g *gen) emitStruct(s structDef) {
	if g.emitted[s.name] {
		return
	}

	// Collect yaml-tagged fields. Interface-typed fields that carry a yaml tag
	// are represented as unknown; interface-typed fields without a yaml tag are
	// simply skipped by the empty-name check below.
	type tsField struct {
		name   string
		tsType string
	}

	var fields []tsField

	var inlineType string // non-empty when a yaml:",inline" field makes the struct a type alias

	for i := range s.typesObj.NumFields() {
		field := s.typesObj.Field(i)

		if !field.Exported() {
			continue
		}

		tag := s.typesObj.Tag(i)

		// yaml:",inline" — the struct's content IS the inlined value.
		if isYAMLInline(tag) && inlineType == "" {
			inlineType = g.typeToTS(field.Type())

			continue
		}

		yamlName := parseYAMLName(tag)
		if yamlName == "" {
			continue
		}

		fields = append(fields, tsField{name: yamlName, tsType: g.typeToTS(field.Type())})
	}

	// Skip structs with no yaml-visible content at all — DeviceConfigSpecSpec is
	// the canonical example: its only field is an interface with no yaml tag.
	if len(fields) == 0 && inlineType == "" {
		return
	}

	// Struct whose only content is an inline field → emit as a type alias.
	// SingleManifest{Object map[string]any yaml:",inline"} → type SingleManifest = {[key:string]: unknown}
	if len(fields) == 0 && inlineType != "" {
		g.emitted[s.name] = true
		fmt.Fprintf(g.output, "\nexport type %s = %s\n", s.name, inlineType)

		return
	}

	// Mark emitted before recursing into field types to break cycles.
	g.emitted[s.name] = true

	g.output.WriteString("\nexport type ")
	g.output.WriteString(s.name)
	g.output.WriteString(" = {\n")

	for _, f := range fields {
		fmt.Fprintf(g.output, "  %s?: %s\n", tsFieldName(f.name), f.tsType)
	}

	g.output.WriteString("}\n")
}

// typeToTS maps a Go type to its TypeScript equivalent.
func (g *gen) typeToTS(t types.Type) string {
	// Resolve type aliases (e.g. os.FileMode = uint32 in Go 1.22+).
	t = types.Unalias(t)

	// Unwrap pointers.
	if ptr, ok := t.(*types.Pointer); ok {
		return g.typeToTS(ptr.Elem())
	}

	// Maps.
	if m, ok := t.(*types.Map); ok {
		return fmt.Sprintf("{[key: %s]: %s}", g.typeToTS(m.Key()), g.typeToTS(m.Elem()))
	}

	// Slices.
	if sl, ok := t.(*types.Slice); ok {
		elem := sl.Elem()
		if basic, ok := elem.(*types.Basic); ok && basic.Kind() == types.Byte {
			return "string" // []byte → base64 string
		}

		return g.typeToTS(elem) + "[]"
	}

	// Named types.
	if named, ok := t.(*types.Named); ok {
		return g.namedToTS(named)
	}

	// Plain built-in types.
	if basic, ok := t.(*types.Basic); ok {
		return basicToTS(basic.Kind())
	}

	return "unknown"
}

// namedToTS handles named types: structs, enums, and well-known external types.
func (g *gen) namedToTS(named *types.Named) string {
	pkg := named.Obj().Pkg()

	// Built-in named types (e.g. error) have no package.
	if pkg == nil {
		return "unknown"
	}

	pkgPath := pkg.Path()
	typeName := named.Obj().Name()
	fqName := pkgPath + "." + typeName

	// Well-known netip types that marshal as strings.
	switch fqName {
	case "net/netip.Addr", "net/netip.Prefix":
		return "string"
	}

	// Scalar overrides for types that don't carry TextMarshaler but have
	// a known primitive YAML representation (time.Duration, url.URL, etc.).
	if scalar, ok := goTypeToScalar[fqName]; ok {
		return scalar
	}

	// Any named type that implements TextMarshaler serializes as a string
	// regardless of its underlying kind or package (covers cel.Expression,
	// Talos enums, etc.).
	if hasMarshalText(named) {
		return "string"
	}

	switch underlying := named.Underlying().(type) {
	case *types.Struct:
		if pkgPath == g.pkg.PkgPath {
			// Same-package struct: ensure it gets emitted.
			g.ensureStructEmitted(typeName, underlying)

			return typeName
		}

		// Cross-package struct: prefer a known TypeScript import (e.g. PEM types
		// from crypto/x509 → common.pb.ts) over emitting inline, so the generated
		// file references the canonical definition rather than duplicating it.
		if tsPath := g.tsImportPath(pkgPath); tsPath != "" {
			if g.imports[tsPath] == nil {
				g.imports[tsPath] = make(map[string]bool)
			}

			g.imports[tsPath][typeName] = true

			return typeName
		}

		// No known import — try to emit inline using its own tags.
		// Some external structs (e.g. OCI specs.Mount) use json: tags rather
		// than yaml: tags — fall back to json names so the type is useful.
		g.ensureStructEmittedWithFallback(typeName, underlying)

		if !g.emitted[typeName] {
			return "unknown"
		}

		return typeName

	case *types.Basic:
		return basicToTS(underlying.Kind())

	case *types.Slice:
		// Named slice type — e.g. net.HardwareAddr = []byte → string.
		elem := underlying.Elem()
		if basic, ok := elem.(*types.Basic); ok && basic.Kind() == types.Byte {
			return "string"
		}

		return g.typeToTS(elem) + "[]"
	}

	return "unknown"
}

// tsImportPath maps a Go package path to the TypeScript import path of the
// file that contains equivalent type definitions, or "" if there is none.
func (g *gen) tsImportPath(goPkgPath string) string {
	// Sibling resources package → adjacent .pb.ts file.
	if siblingPkg, ok := strings.CutPrefix(goPkgPath, resourcesPrefix); ok {
		return "./" + siblingPkg + ".pb"
	}

	// Explicit mapping for packages whose types appear in proto-generated files.
	return goPackageToTSImport[goPkgPath]
}

// ensureStructEmittedWithFallback is like ensureStructEmitted but also
// considers json: tags when yaml: tags are absent. This handles cross-package
// structs such as the OCI runtime-spec Mount that use json: tag conventions.
func (g *gen) ensureStructEmittedWithFallback(name string, s *types.Struct) {
	if g.emitted[name] {
		return
	}

	var fields [][2]string

	for i := range s.NumFields() {
		field := s.Field(i)
		if !field.Exported() {
			continue
		}

		tag := s.Tag(i)

		fieldName := parseYAMLName(tag)
		if fieldName == "" {
			fieldName = parseJSONName(tag) // fall back to json: tag
		}

		if fieldName == "" {
			continue
		}

		fields = append(fields, [2]string{fieldName, g.typeToTS(field.Type())})
	}

	if len(fields) == 0 {
		return
	}

	g.emitted[name] = true

	g.output.WriteString("\nexport type ")
	g.output.WriteString(name)
	g.output.WriteString(" = {\n")

	for _, f := range fields {
		fmt.Fprintf(g.output, "  %s?: %s\n", tsFieldName(f[0]), f[1])
	}

	g.output.WriteString("}\n")
}

// ensureStructEmitted emits a struct that was discovered as a field dependency
// rather than directly from the //gotagsrewrite:gen scan.
func (g *gen) ensureStructEmitted(name string, s *types.Struct) {
	if g.emitted[name] {
		return
	}

	var fields [][2]string

	for i := range s.NumFields() {
		field := s.Field(i)
		if !field.Exported() {
			continue
		}

		yamlName := parseYAMLName(s.Tag(i))
		if yamlName == "" {
			continue
		}

		fields = append(fields, [2]string{yamlName, g.typeToTS(field.Type())})
	}

	if len(fields) == 0 {
		return
	}

	g.emitted[name] = true

	g.output.WriteString("\nexport type ")
	g.output.WriteString(name)
	g.output.WriteString(" = {\n")

	for _, f := range fields {
		fmt.Fprintf(g.output, "  %s?: %s\n", tsFieldName(f[0]), f[1])
	}

	g.output.WriteString("}\n")
}

// hasMarshalText reports whether the type or its pointer has a MarshalText method.
func hasMarshalText(named *types.Named) bool {
	for m := range named.Methods() {
		if m.Name() == "MarshalText" {
			return true
		}
	}

	// Check pointer receiver method set.
	mset := types.NewMethodSet(types.NewPointer(named))

	return mset.Lookup(nil, "MarshalText") != nil
}

// basicToTS maps Go basic kinds to TypeScript primitives.
func basicToTS(k types.BasicKind) string {
	switch k {
	case types.String:
		return "string"
	case types.Bool:
		return "boolean"
	case types.Int, types.Int8, types.Int16, types.Int32, types.Int64,
		types.Uint, types.Uint8, types.Uint16, types.Uint32, types.Uint64,
		types.Float32, types.Float64:
		return "number"
	case types.Invalid, types.Uintptr, types.Complex64, types.Complex128,
		types.UnsafePointer, types.UntypedBool, types.UntypedInt, types.UntypedRune,
		types.UntypedFloat, types.UntypedComplex, types.UntypedString, types.UntypedNil:
		return "unknown"
	}

	return "unknown"
}

// tsFieldName quotes a field name if it is not a valid JavaScript identifier.
// Names with hyphens (e.g. "rx-mini") or that start with a digit (e.g. "1x")
// must be written as quoted property names ('rx-mini', '1x').
func tsFieldName(name string) string {
	for i, r := range name {
		switch {
		case r == '_':
			// always valid
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z':
			// always valid
		case r >= '0' && r <= '9':
			if i == 0 {
				return "'" + name + "'" // digit at start is not a valid identifier
			}
		default:
			return "'" + name + "'"
		}
	}

	return name
}

// parseJSONName extracts the field name from a json: struct tag.
func parseJSONName(tag string) string {
	val := reflect_StructTag(tag).get("json")
	if val == "" || val == "-" {
		return ""
	}

	name, _, _ := strings.Cut(val, ",")
	if name == "-" {
		return ""
	}

	return name
}

// isYAMLInline reports whether the struct tag has yaml:",inline".
func isYAMLInline(tag string) bool {
	val := reflect_StructTag(tag).get("yaml")
	_, opts, _ := strings.Cut(val, ",")

	return strings.Contains(opts, "inline")
}

// parseYAMLName extracts the field name from a struct tag string.
// Returns "" if the field should be skipped (no tag, "-", or inline-only).
func parseYAMLName(tag string) string {
	st := reflect_StructTag(tag)
	val := st.get("yaml")

	if val == "" || val == "-" {
		return ""
	}

	name, _, _ := strings.Cut(val, ",")
	if name == "" || name == "-" {
		return ""
	}

	return name
}

// reflect_StructTag provides minimal struct tag parsing without importing reflect.
type reflect_StructTag string

func (tag reflect_StructTag) get(key string) string {
	s := string(tag)

	for s != "" {
		// Skip leading whitespace.
		i := 0
		for i < len(s) && s[i] == ' ' {
			i++
		}

		s = s[i:]
		if s == "" {
			break
		}

		// Find key:value pair.
		i = 0
		for i < len(s) && s[i] != ':' && s[i] != '"' && s[i] != 0x7f {
			i++
		}

		if i == 0 || i+1 >= len(s) || s[i] != ':' || s[i+1] != '"' {
			break
		}

		name := s[:i]
		s = s[i+1:]

		// Find closing quote.
		i = 1
		for i < len(s) && s[i] != '"' {
			if s[i] == '\\' {
				i++
			}

			i++
		}

		if i >= len(s) {
			break
		}

		if name == key {
			return s[1:i]
		}

		s = s[i+1:]
	}

	return ""
}

// inWorkspaceMode reports whether go is operating in workspace mode by checking
// whether `go env GOWORK` returns a non-empty path.
func inWorkspaceMode(ctx context.Context) bool {
	out, err := exec.CommandContext(ctx, "go", "env", "GOWORK").Output()
	if err != nil {
		return false
	}

	return strings.TrimSpace(string(out)) != ""
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
