// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: omni/specs/ephemeral.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineStatusLinkSpec describes the combination of MessageStatusSpec and SideroLinkSpec and SiderolinkCounterSpec
type MachineStatusLinkSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageStatus     *MachineStatusSpec     `protobuf:"bytes,1,opt,name=message_status,json=messageStatus,proto3" json:"message_status,omitempty"`
	SiderolinkCounter *SiderolinkCounterSpec `protobuf:"bytes,2,opt,name=siderolink_counter,json=siderolinkCounter,proto3" json:"siderolink_counter,omitempty"`
	MachineCreatedAt  int64                  `protobuf:"varint,3,opt,name=machine_created_at,json=machineCreatedAt,proto3" json:"machine_created_at,omitempty"`
	TearingDown       bool                   `protobuf:"varint,4,opt,name=tearing_down,json=tearingDown,proto3" json:"tearing_down,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MachineStatusLinkSpec) Reset() {
	*x = MachineStatusLinkSpec{}
	mi := &file_omni_specs_ephemeral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineStatusLinkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineStatusLinkSpec) ProtoMessage() {}

func (x *MachineStatusLinkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_ephemeral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineStatusLinkSpec.ProtoReflect.Descriptor instead.
func (*MachineStatusLinkSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_ephemeral_proto_rawDescGZIP(), []int{0}
}

func (x *MachineStatusLinkSpec) GetMessageStatus() *MachineStatusSpec {
	if x != nil {
		return x.MessageStatus
	}
	return nil
}

func (x *MachineStatusLinkSpec) GetSiderolinkCounter() *SiderolinkCounterSpec {
	if x != nil {
		return x.SiderolinkCounter
	}
	return nil
}

func (x *MachineStatusLinkSpec) GetMachineCreatedAt() int64 {
	if x != nil {
		return x.MachineCreatedAt
	}
	return 0
}

func (x *MachineStatusLinkSpec) GetTearingDown() bool {
	if x != nil {
		return x.TearingDown
	}
	return false
}

var File_omni_specs_ephemeral_proto protoreflect.FileDescriptor

const file_omni_specs_ephemeral_proto_rawDesc = "" +
	"\n" +
	"\x1aomni/specs/ephemeral.proto\x12\x05specs\x1a\x15omni/specs/omni.proto\x1a\x1bomni/specs/siderolink.proto\"\xf6\x01\n" +
	"\x15MachineStatusLinkSpec\x12?\n" +
	"\x0emessage_status\x18\x01 \x01(\v2\x18.specs.MachineStatusSpecR\rmessageStatus\x12K\n" +
	"\x12siderolink_counter\x18\x02 \x01(\v2\x1c.specs.SiderolinkCounterSpecR\x11siderolinkCounter\x12,\n" +
	"\x12machine_created_at\x18\x03 \x01(\x03R\x10machineCreatedAt\x12!\n" +
	"\ftearing_down\x18\x04 \x01(\bR\vtearingDownB2Z0github.com/siderolabs/omni/client/api/omni/specsb\x06proto3"

var (
	file_omni_specs_ephemeral_proto_rawDescOnce sync.Once
	file_omni_specs_ephemeral_proto_rawDescData []byte
)

func file_omni_specs_ephemeral_proto_rawDescGZIP() []byte {
	file_omni_specs_ephemeral_proto_rawDescOnce.Do(func() {
		file_omni_specs_ephemeral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omni_specs_ephemeral_proto_rawDesc), len(file_omni_specs_ephemeral_proto_rawDesc)))
	})
	return file_omni_specs_ephemeral_proto_rawDescData
}

var file_omni_specs_ephemeral_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_omni_specs_ephemeral_proto_goTypes = []any{
	(*MachineStatusLinkSpec)(nil), // 0: specs.MachineStatusLinkSpec
	(*MachineStatusSpec)(nil),     // 1: specs.MachineStatusSpec
	(*SiderolinkCounterSpec)(nil), // 2: specs.SiderolinkCounterSpec
}
var file_omni_specs_ephemeral_proto_depIdxs = []int32{
	1, // 0: specs.MachineStatusLinkSpec.message_status:type_name -> specs.MachineStatusSpec
	2, // 1: specs.MachineStatusLinkSpec.siderolink_counter:type_name -> specs.SiderolinkCounterSpec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_omni_specs_ephemeral_proto_init() }
func file_omni_specs_ephemeral_proto_init() {
	if File_omni_specs_ephemeral_proto != nil {
		return
	}
	file_omni_specs_omni_proto_init()
	file_omni_specs_siderolink_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omni_specs_ephemeral_proto_rawDesc), len(file_omni_specs_ephemeral_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omni_specs_ephemeral_proto_goTypes,
		DependencyIndexes: file_omni_specs_ephemeral_proto_depIdxs,
		MessageInfos:      file_omni_specs_ephemeral_proto_msgTypes,
	}.Build()
	File_omni_specs_ephemeral_proto = out.File
	file_omni_specs_ephemeral_proto_goTypes = nil
	file_omni_specs_ephemeral_proto_depIdxs = nil
}
