// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: omni/specs/siderolink.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeUniqueTokenStatusSpec_State int32

const (
	NodeUniqueTokenStatusSpec_UNKNOWN     NodeUniqueTokenStatusSpec_State = 0
	NodeUniqueTokenStatusSpec_PERSISTENT  NodeUniqueTokenStatusSpec_State = 1
	NodeUniqueTokenStatusSpec_EPHEMERAL   NodeUniqueTokenStatusSpec_State = 2
	NodeUniqueTokenStatusSpec_NONE        NodeUniqueTokenStatusSpec_State = 3
	NodeUniqueTokenStatusSpec_UNSUPPORTED NodeUniqueTokenStatusSpec_State = 4
)

// Enum value maps for NodeUniqueTokenStatusSpec_State.
var (
	NodeUniqueTokenStatusSpec_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "PERSISTENT",
		2: "EPHEMERAL",
		3: "NONE",
		4: "UNSUPPORTED",
	}
	NodeUniqueTokenStatusSpec_State_value = map[string]int32{
		"UNKNOWN":     0,
		"PERSISTENT":  1,
		"EPHEMERAL":   2,
		"NONE":        3,
		"UNSUPPORTED": 4,
	}
)

func (x NodeUniqueTokenStatusSpec_State) Enum() *NodeUniqueTokenStatusSpec_State {
	p := new(NodeUniqueTokenStatusSpec_State)
	*p = x
	return p
}

func (x NodeUniqueTokenStatusSpec_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeUniqueTokenStatusSpec_State) Descriptor() protoreflect.EnumDescriptor {
	return file_omni_specs_siderolink_proto_enumTypes[0].Descriptor()
}

func (NodeUniqueTokenStatusSpec_State) Type() protoreflect.EnumType {
	return &file_omni_specs_siderolink_proto_enumTypes[0]
}

func (x NodeUniqueTokenStatusSpec_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeUniqueTokenStatusSpec_State.Descriptor instead.
func (NodeUniqueTokenStatusSpec_State) EnumDescriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{11, 0}
}

// SiderolinkConfigSpec describes siderolink wireguard server state to persist it across restarts.
type SiderolinkConfigSpec struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey         string                 `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey          string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	WireguardEndpoint  string                 `protobuf:"bytes,3,opt,name=wireguard_endpoint,json=wireguardEndpoint,proto3" json:"wireguard_endpoint,omitempty"`
	Subnet             string                 `protobuf:"bytes,5,opt,name=subnet,proto3" json:"subnet,omitempty"`
	ServerAddress      string                 `protobuf:"bytes,6,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	InitialJoinToken   string                 `protobuf:"bytes,7,opt,name=initial_join_token,json=initialJoinToken,proto3" json:"initial_join_token,omitempty"`
	AdvertisedEndpoint string                 `protobuf:"bytes,8,opt,name=advertised_endpoint,json=advertisedEndpoint,proto3" json:"advertised_endpoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SiderolinkConfigSpec) Reset() {
	*x = SiderolinkConfigSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiderolinkConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiderolinkConfigSpec) ProtoMessage() {}

func (x *SiderolinkConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiderolinkConfigSpec.ProtoReflect.Descriptor instead.
func (*SiderolinkConfigSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{0}
}

func (x *SiderolinkConfigSpec) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetWireguardEndpoint() string {
	if x != nil {
		return x.WireguardEndpoint
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetSubnet() string {
	if x != nil {
		return x.Subnet
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetInitialJoinToken() string {
	if x != nil {
		return x.InitialJoinToken
	}
	return ""
}

func (x *SiderolinkConfigSpec) GetAdvertisedEndpoint() string {
	if x != nil {
		return x.AdvertisedEndpoint
	}
	return ""
}

// SiderolinkSpec describes each node connection information.
type SiderolinkSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeSubnet      string                 `protobuf:"bytes,1,opt,name=node_subnet,json=nodeSubnet,proto3" json:"node_subnet,omitempty"`
	NodePublicKey   string                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	LastEndpoint    string                 `protobuf:"bytes,3,opt,name=last_endpoint,json=lastEndpoint,proto3" json:"last_endpoint,omitempty"`
	Connected       bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	VirtualAddrport string                 `protobuf:"bytes,7,opt,name=virtual_addrport,json=virtualAddrport,proto3" json:"virtual_addrport,omitempty"`
	// RemoteAddr is the machine address how it's visible from Omni
	// it is determined by reading X-Forwarded-For header coming from the gRPC API.
	RemoteAddr string `protobuf:"bytes,8,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	// Deprecated: Marked as deprecated in omni/specs/siderolink.proto.
	NodeUniqueToken string `protobuf:"bytes,9,opt,name=node_unique_token,json=nodeUniqueToken,proto3" json:"node_unique_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SiderolinkSpec) Reset() {
	*x = SiderolinkSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiderolinkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiderolinkSpec) ProtoMessage() {}

func (x *SiderolinkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiderolinkSpec.ProtoReflect.Descriptor instead.
func (*SiderolinkSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{1}
}

func (x *SiderolinkSpec) GetNodeSubnet() string {
	if x != nil {
		return x.NodeSubnet
	}
	return ""
}

func (x *SiderolinkSpec) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

func (x *SiderolinkSpec) GetLastEndpoint() string {
	if x != nil {
		return x.LastEndpoint
	}
	return ""
}

func (x *SiderolinkSpec) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *SiderolinkSpec) GetVirtualAddrport() string {
	if x != nil {
		return x.VirtualAddrport
	}
	return ""
}

func (x *SiderolinkSpec) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

// Deprecated: Marked as deprecated in omni/specs/siderolink.proto.
func (x *SiderolinkSpec) GetNodeUniqueToken() string {
	if x != nil {
		return x.NodeUniqueToken
	}
	return ""
}

// LinkStatusSpec is created when the link peer event was submitted.
type LinkStatusSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeSubnet      string                 `protobuf:"bytes,1,opt,name=node_subnet,json=nodeSubnet,proto3" json:"node_subnet,omitempty"`
	NodePublicKey   string                 `protobuf:"bytes,2,opt,name=node_public_key,json=nodePublicKey,proto3" json:"node_public_key,omitempty"`
	VirtualAddrport string                 `protobuf:"bytes,3,opt,name=virtual_addrport,json=virtualAddrport,proto3" json:"virtual_addrport,omitempty"`
	// LinkId is the ID of the resource which created the link status.
	LinkId        string `protobuf:"bytes,4,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatusSpec) Reset() {
	*x = LinkStatusSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatusSpec) ProtoMessage() {}

func (x *LinkStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatusSpec.ProtoReflect.Descriptor instead.
func (*LinkStatusSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{2}
}

func (x *LinkStatusSpec) GetNodeSubnet() string {
	if x != nil {
		return x.NodeSubnet
	}
	return ""
}

func (x *LinkStatusSpec) GetNodePublicKey() string {
	if x != nil {
		return x.NodePublicKey
	}
	return ""
}

func (x *LinkStatusSpec) GetVirtualAddrport() string {
	if x != nil {
		return x.VirtualAddrport
	}
	return ""
}

func (x *LinkStatusSpec) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

// SiderolinkConnectionSpec describes each node connection information.
type SiderolinkCounterSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived int64                  `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesSent     int64                  `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LastAlive     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_alive,json=lastAlive,proto3" json:"last_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiderolinkCounterSpec) Reset() {
	*x = SiderolinkCounterSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiderolinkCounterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiderolinkCounterSpec) ProtoMessage() {}

func (x *SiderolinkCounterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiderolinkCounterSpec.ProtoReflect.Descriptor instead.
func (*SiderolinkCounterSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{3}
}

func (x *SiderolinkCounterSpec) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *SiderolinkCounterSpec) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *SiderolinkCounterSpec) GetLastAlive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAlive
	}
	return nil
}

// ConnectionParamsSpec describes generated kernel parameters for connecting
// the Talos node to Omni.
type ConnectionParamsSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Args keeps the generated kernel arguments string.
	Args string `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	// ApiEndpoint is the service gRPC API endpoint (external domain/ip, schema and port).
	ApiEndpoint string `protobuf:"bytes,2,opt,name=api_endpoint,json=apiEndpoint,proto3" json:"api_endpoint,omitempty"`
	// WireguardEndpoint is the service IP visible from the internal SideroLink network.
	WireguardEndpoint string `protobuf:"bytes,3,opt,name=wireguard_endpoint,json=wireguardEndpoint,proto3" json:"wireguard_endpoint,omitempty"`
	// JoinToken is the default join token that can be used to connect to SideroLink.
	JoinToken string `protobuf:"bytes,4,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	// UseGRPCTunnel is a flag to enable gRPC tunneling.
	UseGrpcTunnel bool `protobuf:"varint,5,opt,name=use_grpc_tunnel,json=useGrpcTunnel,proto3" json:"use_grpc_tunnel,omitempty"`
	// EventsPort is the siderolink events port.
	EventsPort int32 `protobuf:"varint,9,opt,name=events_port,json=eventsPort,proto3" json:"events_port,omitempty"`
	// LogsPort is the logs port.
	LogsPort      int32 `protobuf:"varint,10,opt,name=logs_port,json=logsPort,proto3" json:"logs_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionParamsSpec) Reset() {
	*x = ConnectionParamsSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionParamsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionParamsSpec) ProtoMessage() {}

func (x *ConnectionParamsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionParamsSpec.ProtoReflect.Descriptor instead.
func (*ConnectionParamsSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectionParamsSpec) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

func (x *ConnectionParamsSpec) GetApiEndpoint() string {
	if x != nil {
		return x.ApiEndpoint
	}
	return ""
}

func (x *ConnectionParamsSpec) GetWireguardEndpoint() string {
	if x != nil {
		return x.WireguardEndpoint
	}
	return ""
}

func (x *ConnectionParamsSpec) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

func (x *ConnectionParamsSpec) GetUseGrpcTunnel() bool {
	if x != nil {
		return x.UseGrpcTunnel
	}
	return false
}

func (x *ConnectionParamsSpec) GetEventsPort() int32 {
	if x != nil {
		return x.EventsPort
	}
	return 0
}

func (x *ConnectionParamsSpec) GetLogsPort() int32 {
	if x != nil {
		return x.LogsPort
	}
	return 0
}

// PendingMachineStatusSpec describes the spec of the pending machine status resource.
type PendingMachineStatusSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TalosInstalled bool                   `protobuf:"varint,2,opt,name=talos_installed,json=talosInstalled,proto3" json:"talos_installed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PendingMachineStatusSpec) Reset() {
	*x = PendingMachineStatusSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingMachineStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMachineStatusSpec) ProtoMessage() {}

func (x *PendingMachineStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMachineStatusSpec.ProtoReflect.Descriptor instead.
func (*PendingMachineStatusSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{5}
}

func (x *PendingMachineStatusSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PendingMachineStatusSpec) GetTalosInstalled() bool {
	if x != nil {
		return x.TalosInstalled
	}
	return false
}

type JoinConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KernelArgs    []string               `protobuf:"bytes,1,rep,name=kernel_args,json=kernelArgs,proto3" json:"kernel_args,omitempty"`
	Config        string                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinConfig) Reset() {
	*x = JoinConfig{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConfig) ProtoMessage() {}

func (x *JoinConfig) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConfig.ProtoReflect.Descriptor instead.
func (*JoinConfig) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{6}
}

func (x *JoinConfig) GetKernelArgs() []string {
	if x != nil {
		return x.KernelArgs
	}
	return nil
}

func (x *JoinConfig) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

type SiderolinkAPIConfigSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MachineApiAdvertisedUrl is the machine service gRPC API URL (external domain/ip, schema and port).
	// Talos nodes use this API to get the siderolink connection params, key management server also runs there.
	MachineApiAdvertisedUrl string `protobuf:"bytes,1,opt,name=machine_api_advertised_url,json=machineApiAdvertisedUrl,proto3" json:"machine_api_advertised_url,omitempty"`
	// WireguardAdvertisedEndpoint is the service IP visible from the internal SideroLink network.
	WireguardAdvertisedEndpoint string `protobuf:"bytes,2,opt,name=wireguard_advertised_endpoint,json=wireguardAdvertisedEndpoint,proto3" json:"wireguard_advertised_endpoint,omitempty"`
	// EnforceGRPCTunnel is a flag to enable gRPC tunneling.
	EnforceGrpcTunnel bool `protobuf:"varint,3,opt,name=enforce_grpc_tunnel,json=enforceGrpcTunnel,proto3" json:"enforce_grpc_tunnel,omitempty"`
	// EventsPort is the siderolink events port.
	EventsPort int32 `protobuf:"varint,4,opt,name=events_port,json=eventsPort,proto3" json:"events_port,omitempty"`
	// LogsPort is the logs port.
	LogsPort      int32 `protobuf:"varint,5,opt,name=logs_port,json=logsPort,proto3" json:"logs_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiderolinkAPIConfigSpec) Reset() {
	*x = SiderolinkAPIConfigSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiderolinkAPIConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiderolinkAPIConfigSpec) ProtoMessage() {}

func (x *SiderolinkAPIConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiderolinkAPIConfigSpec.ProtoReflect.Descriptor instead.
func (*SiderolinkAPIConfigSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{7}
}

func (x *SiderolinkAPIConfigSpec) GetMachineApiAdvertisedUrl() string {
	if x != nil {
		return x.MachineApiAdvertisedUrl
	}
	return ""
}

func (x *SiderolinkAPIConfigSpec) GetWireguardAdvertisedEndpoint() string {
	if x != nil {
		return x.WireguardAdvertisedEndpoint
	}
	return ""
}

func (x *SiderolinkAPIConfigSpec) GetEnforceGrpcTunnel() bool {
	if x != nil {
		return x.EnforceGrpcTunnel
	}
	return false
}

func (x *SiderolinkAPIConfigSpec) GetEventsPort() int32 {
	if x != nil {
		return x.EventsPort
	}
	return 0
}

func (x *SiderolinkAPIConfigSpec) GetLogsPort() int32 {
	if x != nil {
		return x.LogsPort
	}
	return 0
}

type ProviderJoinConfigSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *JoinConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	JoinToken     string                 `protobuf:"bytes,2,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderJoinConfigSpec) Reset() {
	*x = ProviderJoinConfigSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderJoinConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderJoinConfigSpec) ProtoMessage() {}

func (x *ProviderJoinConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderJoinConfigSpec.ProtoReflect.Descriptor instead.
func (*ProviderJoinConfigSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderJoinConfigSpec) GetConfig() *JoinConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ProviderJoinConfigSpec) GetJoinToken() string {
	if x != nil {
		return x.JoinToken
	}
	return ""
}

type MachineJoinConfigSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *JoinConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineJoinConfigSpec) Reset() {
	*x = MachineJoinConfigSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineJoinConfigSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineJoinConfigSpec) ProtoMessage() {}

func (x *MachineJoinConfigSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineJoinConfigSpec.ProtoReflect.Descriptor instead.
func (*MachineJoinConfigSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{9}
}

func (x *MachineJoinConfigSpec) GetConfig() *JoinConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type NodeUniqueTokenSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token is the per node join token which is saved in the Node META partition after
	// the machine is accepted in Omni.
	// Only for Talos >= 1.6.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUniqueTokenSpec) Reset() {
	*x = NodeUniqueTokenSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUniqueTokenSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUniqueTokenSpec) ProtoMessage() {}

func (x *NodeUniqueTokenSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUniqueTokenSpec.ProtoReflect.Descriptor instead.
func (*NodeUniqueTokenSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{10}
}

func (x *NodeUniqueTokenSpec) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type NodeUniqueTokenStatusSpec struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	State         NodeUniqueTokenStatusSpec_State `protobuf:"varint,1,opt,name=state,proto3,enum=specs.NodeUniqueTokenStatusSpec_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeUniqueTokenStatusSpec) Reset() {
	*x = NodeUniqueTokenStatusSpec{}
	mi := &file_omni_specs_siderolink_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUniqueTokenStatusSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUniqueTokenStatusSpec) ProtoMessage() {}

func (x *NodeUniqueTokenStatusSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_siderolink_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUniqueTokenStatusSpec.ProtoReflect.Descriptor instead.
func (*NodeUniqueTokenStatusSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_siderolink_proto_rawDescGZIP(), []int{11}
}

func (x *NodeUniqueTokenStatusSpec) GetState() NodeUniqueTokenStatusSpec_State {
	if x != nil {
		return x.State
	}
	return NodeUniqueTokenStatusSpec_UNKNOWN
}

var File_omni_specs_siderolink_proto protoreflect.FileDescriptor

const file_omni_specs_siderolink_proto_rawDesc = "" +
	"\n" +
	"\x1bomni/specs/siderolink.proto\x12\x05specs\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x02\n" +
	"\x14SiderolinkConfigSpec\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12-\n" +
	"\x12wireguard_endpoint\x18\x03 \x01(\tR\x11wireguardEndpoint\x12\x16\n" +
	"\x06subnet\x18\x05 \x01(\tR\x06subnet\x12%\n" +
	"\x0eserver_address\x18\x06 \x01(\tR\rserverAddress\x12,\n" +
	"\x12initial_join_token\x18\a \x01(\tR\x10initialJoinToken\x12/\n" +
	"\x13advertised_endpoint\x18\b \x01(\tR\x12advertisedEndpoint\"\xa4\x02\n" +
	"\x0eSiderolinkSpec\x12\x1f\n" +
	"\vnode_subnet\x18\x01 \x01(\tR\n" +
	"nodeSubnet\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\tR\rnodePublicKey\x12#\n" +
	"\rlast_endpoint\x18\x03 \x01(\tR\flastEndpoint\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\x12)\n" +
	"\x10virtual_addrport\x18\a \x01(\tR\x0fvirtualAddrport\x12\x1f\n" +
	"\vremote_addr\x18\b \x01(\tR\n" +
	"remoteAddr\x12.\n" +
	"\x11node_unique_token\x18\t \x01(\tB\x02\x18\x01R\x0fnodeUniqueTokenJ\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\x9d\x01\n" +
	"\x0eLinkStatusSpec\x12\x1f\n" +
	"\vnode_subnet\x18\x01 \x01(\tR\n" +
	"nodeSubnet\x12&\n" +
	"\x0fnode_public_key\x18\x02 \x01(\tR\rnodePublicKey\x12)\n" +
	"\x10virtual_addrport\x18\x03 \x01(\tR\x0fvirtualAddrport\x12\x17\n" +
	"\alink_id\x18\x04 \x01(\tR\x06linkId\"\x98\x01\n" +
	"\x15SiderolinkCounterSpec\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x03R\rbytesReceived\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x02 \x01(\x03R\tbytesSent\x129\n" +
	"\n" +
	"last_alive\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tlastAlive\"\x81\x02\n" +
	"\x14ConnectionParamsSpec\x12\x12\n" +
	"\x04args\x18\x01 \x01(\tR\x04args\x12!\n" +
	"\fapi_endpoint\x18\x02 \x01(\tR\vapiEndpoint\x12-\n" +
	"\x12wireguard_endpoint\x18\x03 \x01(\tR\x11wireguardEndpoint\x12\x1d\n" +
	"\n" +
	"join_token\x18\x04 \x01(\tR\tjoinToken\x12&\n" +
	"\x0fuse_grpc_tunnel\x18\x05 \x01(\bR\ruseGrpcTunnel\x12\x1f\n" +
	"\vevents_port\x18\t \x01(\x05R\n" +
	"eventsPort\x12\x1b\n" +
	"\tlogs_port\x18\n" +
	" \x01(\x05R\blogsPort\"Y\n" +
	"\x18PendingMachineStatusSpec\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12'\n" +
	"\x0ftalos_installed\x18\x02 \x01(\bR\x0etalosInstalled\"E\n" +
	"\n" +
	"JoinConfig\x12\x1f\n" +
	"\vkernel_args\x18\x01 \x03(\tR\n" +
	"kernelArgs\x12\x16\n" +
	"\x06config\x18\x02 \x01(\tR\x06config\"\x88\x02\n" +
	"\x17SiderolinkAPIConfigSpec\x12;\n" +
	"\x1amachine_api_advertised_url\x18\x01 \x01(\tR\x17machineApiAdvertisedUrl\x12B\n" +
	"\x1dwireguard_advertised_endpoint\x18\x02 \x01(\tR\x1bwireguardAdvertisedEndpoint\x12.\n" +
	"\x13enforce_grpc_tunnel\x18\x03 \x01(\bR\x11enforceGrpcTunnel\x12\x1f\n" +
	"\vevents_port\x18\x04 \x01(\x05R\n" +
	"eventsPort\x12\x1b\n" +
	"\tlogs_port\x18\x05 \x01(\x05R\blogsPort\"b\n" +
	"\x16ProviderJoinConfigSpec\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.specs.JoinConfigR\x06config\x12\x1d\n" +
	"\n" +
	"join_token\x18\x02 \x01(\tR\tjoinToken\"B\n" +
	"\x15MachineJoinConfigSpec\x12)\n" +
	"\x06config\x18\x01 \x01(\v2\x11.specs.JoinConfigR\x06config\"+\n" +
	"\x13NodeUniqueTokenSpec\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xa9\x01\n" +
	"\x19NodeUniqueTokenStatusSpec\x12<\n" +
	"\x05state\x18\x01 \x01(\x0e2&.specs.NodeUniqueTokenStatusSpec.StateR\x05state\"N\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"PERSISTENT\x10\x01\x12\r\n" +
	"\tEPHEMERAL\x10\x02\x12\b\n" +
	"\x04NONE\x10\x03\x12\x0f\n" +
	"\vUNSUPPORTED\x10\x04B2Z0github.com/siderolabs/omni/client/api/omni/specsb\x06proto3"

var (
	file_omni_specs_siderolink_proto_rawDescOnce sync.Once
	file_omni_specs_siderolink_proto_rawDescData []byte
)

func file_omni_specs_siderolink_proto_rawDescGZIP() []byte {
	file_omni_specs_siderolink_proto_rawDescOnce.Do(func() {
		file_omni_specs_siderolink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omni_specs_siderolink_proto_rawDesc), len(file_omni_specs_siderolink_proto_rawDesc)))
	})
	return file_omni_specs_siderolink_proto_rawDescData
}

var file_omni_specs_siderolink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_omni_specs_siderolink_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_omni_specs_siderolink_proto_goTypes = []any{
	(NodeUniqueTokenStatusSpec_State)(0), // 0: specs.NodeUniqueTokenStatusSpec.State
	(*SiderolinkConfigSpec)(nil),         // 1: specs.SiderolinkConfigSpec
	(*SiderolinkSpec)(nil),               // 2: specs.SiderolinkSpec
	(*LinkStatusSpec)(nil),               // 3: specs.LinkStatusSpec
	(*SiderolinkCounterSpec)(nil),        // 4: specs.SiderolinkCounterSpec
	(*ConnectionParamsSpec)(nil),         // 5: specs.ConnectionParamsSpec
	(*PendingMachineStatusSpec)(nil),     // 6: specs.PendingMachineStatusSpec
	(*JoinConfig)(nil),                   // 7: specs.JoinConfig
	(*SiderolinkAPIConfigSpec)(nil),      // 8: specs.SiderolinkAPIConfigSpec
	(*ProviderJoinConfigSpec)(nil),       // 9: specs.ProviderJoinConfigSpec
	(*MachineJoinConfigSpec)(nil),        // 10: specs.MachineJoinConfigSpec
	(*NodeUniqueTokenSpec)(nil),          // 11: specs.NodeUniqueTokenSpec
	(*NodeUniqueTokenStatusSpec)(nil),    // 12: specs.NodeUniqueTokenStatusSpec
	(*timestamppb.Timestamp)(nil),        // 13: google.protobuf.Timestamp
}
var file_omni_specs_siderolink_proto_depIdxs = []int32{
	13, // 0: specs.SiderolinkCounterSpec.last_alive:type_name -> google.protobuf.Timestamp
	7,  // 1: specs.ProviderJoinConfigSpec.config:type_name -> specs.JoinConfig
	7,  // 2: specs.MachineJoinConfigSpec.config:type_name -> specs.JoinConfig
	0,  // 3: specs.NodeUniqueTokenStatusSpec.state:type_name -> specs.NodeUniqueTokenStatusSpec.State
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_omni_specs_siderolink_proto_init() }
func file_omni_specs_siderolink_proto_init() {
	if File_omni_specs_siderolink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omni_specs_siderolink_proto_rawDesc), len(file_omni_specs_siderolink_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omni_specs_siderolink_proto_goTypes,
		DependencyIndexes: file_omni_specs_siderolink_proto_depIdxs,
		EnumInfos:         file_omni_specs_siderolink_proto_enumTypes,
		MessageInfos:      file_omni_specs_siderolink_proto_msgTypes,
	}.Build()
	File_omni_specs_siderolink_proto = out.File
	file_omni_specs_siderolink_proto_goTypes = nil
	file_omni_specs_siderolink_proto_depIdxs = nil
}
