// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: omni/specs/system.proto

package specs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DBVersionSpec keeps the current version of the COSI DB.
type DBVersionSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBVersionSpec) Reset() {
	*x = DBVersionSpec{}
	mi := &file_omni_specs_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBVersionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBVersionSpec) ProtoMessage() {}

func (x *DBVersionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBVersionSpec.ProtoReflect.Descriptor instead.
func (*DBVersionSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_system_proto_rawDescGZIP(), []int{0}
}

func (x *DBVersionSpec) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// SysVersionSpec keeps the current version of Omni.
type SysVersionSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BackendVersion    string                 `protobuf:"bytes,1,opt,name=backend_version,json=backendVersion,proto3" json:"backend_version,omitempty"`
	InstanceName      string                 `protobuf:"bytes,2,opt,name=instance_name,json=instanceName,proto3" json:"instance_name,omitempty"`
	BackendApiVersion uint32                 `protobuf:"varint,3,opt,name=backend_api_version,json=backendApiVersion,proto3" json:"backend_api_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SysVersionSpec) Reset() {
	*x = SysVersionSpec{}
	mi := &file_omni_specs_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysVersionSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysVersionSpec) ProtoMessage() {}

func (x *SysVersionSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysVersionSpec.ProtoReflect.Descriptor instead.
func (*SysVersionSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_system_proto_rawDescGZIP(), []int{1}
}

func (x *SysVersionSpec) GetBackendVersion() string {
	if x != nil {
		return x.BackendVersion
	}
	return ""
}

func (x *SysVersionSpec) GetInstanceName() string {
	if x != nil {
		return x.InstanceName
	}
	return ""
}

func (x *SysVersionSpec) GetBackendApiVersion() uint32 {
	if x != nil {
		return x.BackendApiVersion
	}
	return 0
}

// CertRefreshTickSpec is a certificate refresh tick.
type CertRefreshTickSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertRefreshTickSpec) Reset() {
	*x = CertRefreshTickSpec{}
	mi := &file_omni_specs_system_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertRefreshTickSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertRefreshTickSpec) ProtoMessage() {}

func (x *CertRefreshTickSpec) ProtoReflect() protoreflect.Message {
	mi := &file_omni_specs_system_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertRefreshTickSpec.ProtoReflect.Descriptor instead.
func (*CertRefreshTickSpec) Descriptor() ([]byte, []int) {
	return file_omni_specs_system_proto_rawDescGZIP(), []int{2}
}

var File_omni_specs_system_proto protoreflect.FileDescriptor

const file_omni_specs_system_proto_rawDesc = "" +
	"\n" +
	"\x17omni/specs/system.proto\x12\x05specs\")\n" +
	"\rDBVersionSpec\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"\x8e\x01\n" +
	"\x0eSysVersionSpec\x12'\n" +
	"\x0fbackend_version\x18\x01 \x01(\tR\x0ebackendVersion\x12#\n" +
	"\rinstance_name\x18\x02 \x01(\tR\finstanceName\x12.\n" +
	"\x13backend_api_version\x18\x03 \x01(\rR\x11backendApiVersion\"\x15\n" +
	"\x13CertRefreshTickSpecB2Z0github.com/siderolabs/omni/client/api/omni/specsb\x06proto3"

var (
	file_omni_specs_system_proto_rawDescOnce sync.Once
	file_omni_specs_system_proto_rawDescData []byte
)

func file_omni_specs_system_proto_rawDescGZIP() []byte {
	file_omni_specs_system_proto_rawDescOnce.Do(func() {
		file_omni_specs_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omni_specs_system_proto_rawDesc), len(file_omni_specs_system_proto_rawDesc)))
	})
	return file_omni_specs_system_proto_rawDescData
}

var file_omni_specs_system_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_omni_specs_system_proto_goTypes = []any{
	(*DBVersionSpec)(nil),       // 0: specs.DBVersionSpec
	(*SysVersionSpec)(nil),      // 1: specs.SysVersionSpec
	(*CertRefreshTickSpec)(nil), // 2: specs.CertRefreshTickSpec
}
var file_omni_specs_system_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_omni_specs_system_proto_init() }
func file_omni_specs_system_proto_init() {
	if File_omni_specs_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omni_specs_system_proto_rawDesc), len(file_omni_specs_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_omni_specs_system_proto_goTypes,
		DependencyIndexes: file_omni_specs_system_proto_depIdxs,
		MessageInfos:      file_omni_specs_system_proto_msgTypes,
	}.Build()
	File_omni_specs_system_proto = out.File
	file_omni_specs_system_proto_goTypes = nil
	file_omni_specs_system_proto_depIdxs = nil
}
