apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omni.fullname" . }}
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYamlPretty | nindent 4 }}
