// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// Package kubeconfig validates kubeconfigs received from the Omni API.
package kubeconfig

import (
	"bytes"
	"crypto/tls"
	stdlibx509 "crypto/x509"
	"encoding/pem"
	"errors"
	"fmt"
	"maps"
	"net/url"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"

	"k8s.io/client-go/tools/clientcmd"
	clientcmdapi "k8s.io/client-go/tools/clientcmd/api"

	"github.com/siderolabs/omni/client/pkg/constants"
)

// defaultNamespace is the namespace Omni always sets on the generated context.
const defaultNamespace = "default"

// ErrInvalidKubeconfig is returned when the kubeconfig doesn't match the structure Omni generates.
var ErrInvalidKubeconfig = errors.New("kubeconfig doesn't match the structure generated by Omni")

// Validate checks that the kubeconfig matches one of the structures Omni generates.
//
// All of them have a single cluster, a single user and a single context tying them together.
// The user is either the OIDC exec credential plugin, a service account token, or a break-glass client certificate.
//
// Every kubeconfig received over the Omni API should go through this before it is used
// to build a Kubernetes client or written to the operator's filesystem.
func Validate(data []byte) error {
	config, err := clientcmd.Load(data)
	if err != nil {
		return fmt.Errorf("error parsing kubeconfig: %w", err)
	}

	return validate(config)
}

//nolint:gocyclo,cyclop
func validate(config *clientcmdapi.Config) error {
	var multiErr []error

	// clientcmd.Load strips the TypeMeta while decoding, so an empty value here means
	// "not present in the decoded config". Only a mismatching value can be rejected.
	if config.Kind != "" && config.Kind != "Config" {
		multiErr = append(multiErr, fmt.Errorf("unexpected kind %q", config.Kind))
	}

	if config.APIVersion != "" && config.APIVersion != "v1" {
		multiErr = append(multiErr, fmt.Errorf("unexpected apiVersion %q", config.APIVersion))
	}

	if config.Preferences.Colors || len(config.Preferences.Extensions) > 0 {
		multiErr = append(multiErr, errors.New("top-level field \"preferences\" is not allowed"))
	}

	if len(config.Extensions) > 0 {
		multiErr = append(multiErr, errors.New("top-level field \"extensions\" is not allowed"))
	}

	clusterName, cluster, err := single(config.Clusters, "cluster")
	if err != nil {
		multiErr = append(multiErr, err)
	} else {
		multiErr = append(multiErr, validateString("cluster name", clusterName))
		multiErr = append(multiErr, validateCluster(cluster)...)
	}

	authInfoName, authInfo, err := single(config.AuthInfos, "user")
	if err != nil {
		multiErr = append(multiErr, err)
	} else {
		multiErr = append(multiErr, validateString("user name", authInfoName))
		multiErr = append(multiErr, validateAuthInfo(authInfo)...)
	}

	if cluster != nil && authInfo != nil {
		multiErr = append(multiErr, validateCertificateAuthority(cluster, authInfo)...)
	}

	contextName, kubeContext, err := single(config.Contexts, "context")
	if err != nil {
		multiErr = append(multiErr, err)
	} else {
		multiErr = append(multiErr, validateString("context name", contextName))
		multiErr = append(multiErr, validateContext(kubeContext, clusterName, authInfoName)...)

		if config.CurrentContext != contextName {
			multiErr = append(multiErr, fmt.Errorf("current-context %q doesn't match the only context %q", config.CurrentContext, contextName))
		}
	}

	if err = errors.Join(multiErr...); err != nil {
		return fmt.Errorf("%w: %w", ErrInvalidKubeconfig, err)
	}

	return nil
}

func validateCluster(cluster *clientcmdapi.Cluster) []error {
	var multiErr []error

	switch u, err := url.Parse(cluster.Server); {
	case cluster.Server == "":
		multiErr = append(multiErr, errors.New("cluster field \"server\" is not set"))
	case err != nil:
		multiErr = append(multiErr, fmt.Errorf("error parsing cluster field \"server\": %w", err))
	case u.Scheme != "https" && u.Scheme != "http":
		multiErr = append(multiErr, fmt.Errorf("unexpected cluster server URL scheme %q", u.Scheme))
	case u.Host == "":
		multiErr = append(multiErr, errors.New("cluster server URL has no host"))
	case u.User != nil:
		multiErr = append(multiErr, errors.New("cluster server URL has embedded credentials"))
	}

	return append(multiErr, disallowed("cluster", map[string]bool{
		"certificate-authority":    cluster.CertificateAuthority != "",
		"disable-compression":      cluster.DisableCompression,
		"extensions":               len(cluster.Extensions) > 0,
		"insecure-skip-tls-verify": cluster.InsecureSkipTLSVerify,
		"proxy-url":                cluster.ProxyURL != "",
		"tls-server-name":          cluster.TLSServerName != "",
	})...)
}

// validateCertificateAuthority checks that the cluster CA is set exactly when the user authenticates with a client certificate.
//
// The break-glass kubeconfig carries the cluster CA. The Kubernetes proxy is reached via the system trust store, so the other kubeconfigs have none.
func validateCertificateAuthority(cluster *clientcmdapi.Cluster, authInfo *clientcmdapi.AuthInfo) []error {
	certificateAuth := len(authInfo.ClientCertificateData) > 0

	switch {
	case certificateAuth && len(cluster.CertificateAuthorityData) == 0:
		return []error{errors.New("cluster field \"certificate-authority-data\" is not set")}
	case !certificateAuth && len(cluster.CertificateAuthorityData) > 0:
		return []error{errors.New("cluster field \"certificate-authority-data\" is only allowed with client certificate authentication")}
	case certificateAuth:
		if err := validateCertificates(cluster.CertificateAuthorityData); err != nil {
			return []error{fmt.Errorf("invalid cluster field \"certificate-authority-data\": %w", err)}
		}
	}

	return nil
}

func validateAuthInfo(authInfo *clientcmdapi.AuthInfo) []error {
	var multiErr []error

	// exactly one authentication method must be set
	switch {
	case authInfo.Exec != nil:
		multiErr = append(multiErr, validateExec(authInfo.Exec)...)
		multiErr = append(multiErr, disallowed("user", map[string]bool{
			"client-certificate-data": len(authInfo.ClientCertificateData) > 0,
			"client-key-data":         len(authInfo.ClientKeyData) > 0,
			"token":                   authInfo.Token != "",
		})...)
	case authInfo.Token != "":
		multiErr = append(multiErr, validateString("user field \"token\"", authInfo.Token))
		multiErr = append(multiErr, disallowed("user", map[string]bool{
			"client-certificate-data": len(authInfo.ClientCertificateData) > 0,
			"client-key-data":         len(authInfo.ClientKeyData) > 0,
		})...)
	case len(authInfo.ClientCertificateData) == 0:
		multiErr = append(multiErr, errors.New("user has no authentication method set"))
	case len(authInfo.ClientKeyData) == 0:
		multiErr = append(multiErr, errors.New("user field \"client-key-data\" is not set"))
	default:
		if err := validateCertificates(authInfo.ClientCertificateData); err != nil {
			multiErr = append(multiErr, fmt.Errorf("invalid user field \"client-certificate-data\": %w", err))
		}

		// this also checks that the key matches the certificate
		if _, err := tls.X509KeyPair(authInfo.ClientCertificateData, authInfo.ClientKeyData); err != nil {
			multiErr = append(multiErr, fmt.Errorf("invalid client certificate and key pair: %w", err))
		}
	}

	return append(multiErr, disallowed("user", map[string]bool{
		"act-as":             authInfo.Impersonate != "",
		"act-as-groups":      len(authInfo.ImpersonateGroups) > 0,
		"act-as-uid":         authInfo.ImpersonateUID != "",
		"act-as-user-extra":  len(authInfo.ImpersonateUserExtra) > 0,
		"auth-provider":      authInfo.AuthProvider != nil,
		"client-certificate": authInfo.ClientCertificate != "",
		"client-key":         authInfo.ClientKey != "",
		"extensions":         len(authInfo.Extensions) > 0,
		"password":           authInfo.Password != "",
		"tokenFile":          authInfo.TokenFile != "",
		"username":           authInfo.Username != "",
	})...)
}

const (
	execCommand     = "kubectl"
	execAPIVersion  = "client.authentication.k8s.io/v1"
	execRedirectArg = "--oidc-redirect-url=" + constants.KeyCodeRedirectURL
	execGrantArg    = "--grant-type="
	execCacheArg    = "--token-cache-dir="
)

// execArgsPrefix is the fixed start of the exec args Omni generates after "oidc-login get-token", each followed by a value.
var execArgsPrefix = []string{"--oidc-issuer-url=", "--oidc-client-id=", "--oidc-extra-scope=cluster:"}

// execGrantTypes are the grant types Omni accepts in the kubeconfig request.
var execGrantTypes = []string{"auto", "authcode", "authcode-keyboard"}

// validateExec checks that the exec credential plugin is exactly the kubelogin invocation Omni generates.
func validateExec(exec *clientcmdapi.ExecConfig) []error {
	var multiErr []error

	if exec.Command != execCommand {
		multiErr = append(multiErr, fmt.Errorf("unexpected exec command %q", exec.Command))
	}

	if exec.APIVersion != execAPIVersion {
		multiErr = append(multiErr, fmt.Errorf("unexpected exec apiVersion %q", exec.APIVersion))
	}

	if exec.InteractiveMode != clientcmdapi.IfAvailableExecInteractiveMode {
		multiErr = append(multiErr, fmt.Errorf("unexpected exec interactiveMode %q", exec.InteractiveMode))
	}

	multiErr = append(multiErr, validateExecArgs(exec.Args)...)

	return append(multiErr, disallowed("exec", map[string]bool{
		"env":                exec.Env != nil,
		"installHint":        exec.InstallHint != "",
		"provideClusterInfo": exec.ProvideClusterInfo,
	})...)
}

// validateExecArgs checks the exec args. They must be the fixed prefix, then an optional grant type with the fixed redirect URL,
// then an optional token cache directory, and nothing else.
func validateExecArgs(args []string) []error {
	var multiErr []error

	for _, arg := range args {
		multiErr = append(multiErr, validateString("exec arg", arg))
	}

	if len(args) < 2+len(execArgsPrefix) || args[0] != "oidc-login" || args[1] != "get-token" {
		return append(multiErr, errors.New("exec args must start with \"oidc-login get-token\" followed by the issuer URL, client ID and cluster scope"))
	}

	for i, prefix := range execArgsPrefix {
		if arg := args[2+i]; !strings.HasPrefix(arg, prefix) || len(arg) == len(prefix) {
			multiErr = append(multiErr, fmt.Errorf("exec arg %q must be %q followed by a value", arg, prefix))
		}
	}

	rest := args[2+len(execArgsPrefix):]

	if len(rest) > 0 && strings.HasPrefix(rest[0], execGrantArg) {
		if !slices.Contains(execGrantTypes, strings.TrimPrefix(rest[0], execGrantArg)) {
			multiErr = append(multiErr, fmt.Errorf("unexpected exec arg %q", rest[0]))
		}

		if len(rest) < 2 || rest[1] != execRedirectArg {
			return append(multiErr, fmt.Errorf("exec arg %q must be followed by %q", rest[0], execRedirectArg))
		}

		rest = rest[2:]
	}

	if len(rest) > 0 && strings.HasPrefix(rest[0], execCacheArg) && len(rest[0]) > len(execCacheArg) {
		rest = rest[1:]
	}

	if len(rest) > 0 {
		multiErr = append(multiErr, fmt.Errorf("unexpected exec args %q", rest))
	}

	return multiErr
}

// validateContext validates the context. clusterName and authInfoName are empty if the
// cluster or user sections failed to validate, in which case there is nothing to cross-check against.
func validateContext(kubeContext *clientcmdapi.Context, clusterName, authInfoName string) []error {
	var multiErr []error

	if clusterName != "" && kubeContext.Cluster != clusterName {
		multiErr = append(multiErr, fmt.Errorf("context references cluster %q, expected %q", kubeContext.Cluster, clusterName))
	}

	if authInfoName != "" && kubeContext.AuthInfo != authInfoName {
		multiErr = append(multiErr, fmt.Errorf("context references user %q, expected %q", kubeContext.AuthInfo, authInfoName))
	}

	if kubeContext.Namespace != defaultNamespace {
		multiErr = append(multiErr, fmt.Errorf("unexpected context namespace %q, expected %q", kubeContext.Namespace, defaultNamespace))
	}

	return append(multiErr, disallowed("context", map[string]bool{
		"extensions": len(kubeContext.Extensions) > 0,
	})...)
}

// disallowed builds an error for each field which Omni never generates but which is set.
func disallowed(kind string, fields map[string]bool) []error {
	var multiErr []error

	for _, name := range slices.Sorted(maps.Keys(fields)) {
		if fields[name] {
			multiErr = append(multiErr, fmt.Errorf("%s field %q is not allowed", kind, name))
		}
	}

	return multiErr
}

// validateCertificates checks that data is a non-empty sequence of PEM-encoded certificates
// and nothing else.
func validateCertificates(data []byte) error {
	rest := data

	var count int

	for {
		var block *pem.Block

		if block, rest = pem.Decode(rest); block == nil {
			break
		}

		if block.Type != "CERTIFICATE" {
			return fmt.Errorf("unexpected PEM block type %q", block.Type)
		}

		if _, err := stdlibx509.ParseCertificate(block.Bytes); err != nil {
			return fmt.Errorf("error parsing certificate: %w", err)
		}

		count++
	}

	if count == 0 {
		return errors.New("no PEM-encoded certificates found")
	}

	if len(bytes.TrimSpace(rest)) > 0 {
		return errors.New("trailing data after the PEM-encoded certificates")
	}

	return nil
}

// validateString rejects values which Omni would never generate. They would end up
// in the operator's kubeconfig, and on their terminal, as-is.
func validateString(what, value string) error {
	switch {
	case value == "":
		return fmt.Errorf("%s is empty", what)
	case !utf8.ValidString(value):
		return fmt.Errorf("%s is not valid UTF-8", what)
	case strings.ContainsFunc(value, unicode.IsControl):
		return fmt.Errorf("%s contains control characters", what)
	}

	return nil
}

// single returns the only entry of the map, or an error if there is not exactly one.
func single[T any](m map[string]*T, kind string) (string, *T, error) {
	if len(m) != 1 {
		return "", nil, fmt.Errorf("expected exactly one %s, got %d", kind, len(m))
	}

	for name, value := range m {
		if value == nil {
			return "", nil, fmt.Errorf("%s %q is empty", kind, name)
		}

		return name, value, nil
	}

	panic("unreachable")
}
