apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omni-v2.fullname" . }}
  labels:
    {{- include "omni-v2.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYamlPretty | nindent 4 }}
