apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-v2.fullname" . }}
  labels:
    {{- include "omni-v2.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
{{- range $key, $value := .Values.secret.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
