// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: omni/imagefactory/imagefactory.proto

package imagefactory

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Arch is the machine architecture an artifact is built for.
type Arch int32

const (
	Arch_UNKNOWN_ARCH Arch = 0
	Arch_AMD64        Arch = 1
	Arch_ARM64        Arch = 2
)

// Enum value maps for Arch.
var (
	Arch_name = map[int32]string{
		0: "UNKNOWN_ARCH",
		1: "AMD64",
		2: "ARM64",
	}
	Arch_value = map[string]int32{
		"UNKNOWN_ARCH": 0,
		"AMD64":        1,
		"ARM64":        2,
	}
)

func (x Arch) Enum() *Arch {
	p := new(Arch)
	*p = x
	return p
}

func (x Arch) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Arch) Descriptor() protoreflect.EnumDescriptor {
	return file_omni_imagefactory_imagefactory_proto_enumTypes[0].Descriptor()
}

func (Arch) Type() protoreflect.EnumType {
	return &file_omni_imagefactory_imagefactory_proto_enumTypes[0]
}

func (x Arch) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Arch.Descriptor instead.
func (Arch) EnumDescriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{0}
}

// VulnerabilityReportFormat selects the format a vulnerability scan report is served in. The
// factory publishes the same scan under each of these.
type VulnerabilityReportFormat int32

const (
	VulnerabilityReportFormat_UNKNOWN_FORMAT VulnerabilityReportFormat = 0
	// Grype's native JSON report.
	VulnerabilityReportFormat_JSON VulnerabilityReportFormat = 1
	// SARIF, as consumed by code scanning tools.
	VulnerabilityReportFormat_SARIF VulnerabilityReportFormat = 2
	// CycloneDX VEX.
	VulnerabilityReportFormat_CYCLONEDX VulnerabilityReportFormat = 3
	// The human-readable table Grype prints.
	VulnerabilityReportFormat_TABLE VulnerabilityReportFormat = 4
)

// Enum value maps for VulnerabilityReportFormat.
var (
	VulnerabilityReportFormat_name = map[int32]string{
		0: "UNKNOWN_FORMAT",
		1: "JSON",
		2: "SARIF",
		3: "CYCLONEDX",
		4: "TABLE",
	}
	VulnerabilityReportFormat_value = map[string]int32{
		"UNKNOWN_FORMAT": 0,
		"JSON":           1,
		"SARIF":          2,
		"CYCLONEDX":      3,
		"TABLE":          4,
	}
)

func (x VulnerabilityReportFormat) Enum() *VulnerabilityReportFormat {
	p := new(VulnerabilityReportFormat)
	*p = x
	return p
}

func (x VulnerabilityReportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VulnerabilityReportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_omni_imagefactory_imagefactory_proto_enumTypes[1].Descriptor()
}

func (VulnerabilityReportFormat) Type() protoreflect.EnumType {
	return &file_omni_imagefactory_imagefactory_proto_enumTypes[1]
}

func (x VulnerabilityReportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VulnerabilityReportFormat.Descriptor instead.
func (VulnerabilityReportFormat) EnumDescriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{1}
}

type VulnerabilityReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SchematicID is the hex-encoded SHA-256 of the schematic the report covers.
	SchematicId string `protobuf:"bytes,1,opt,name=schematic_id,json=schematicId,proto3" json:"schematic_id,omitempty"`
	// TalosVersion is the Talos version the schematic was built for.
	TalosVersion string `protobuf:"bytes,2,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	// Arch is the architecture the schematic was built for.
	Arch Arch `protobuf:"varint,3,opt,name=arch,proto3,enum=imagefactory.Arch" json:"arch,omitempty"`
	// Format is the format to serve the report in.
	Format        VulnerabilityReportFormat `protobuf:"varint,4,opt,name=format,proto3,enum=imagefactory.VulnerabilityReportFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VulnerabilityReportRequest) Reset() {
	*x = VulnerabilityReportRequest{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityReportRequest) ProtoMessage() {}

func (x *VulnerabilityReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityReportRequest.ProtoReflect.Descriptor instead.
func (*VulnerabilityReportRequest) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{0}
}

func (x *VulnerabilityReportRequest) GetSchematicId() string {
	if x != nil {
		return x.SchematicId
	}
	return ""
}

func (x *VulnerabilityReportRequest) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *VulnerabilityReportRequest) GetArch() Arch {
	if x != nil {
		return x.Arch
	}
	return Arch_UNKNOWN_ARCH
}

func (x *VulnerabilityReportRequest) GetFormat() VulnerabilityReportFormat {
	if x != nil {
		return x.Format
	}
	return VulnerabilityReportFormat_UNKNOWN_FORMAT
}

type VulnerabilityReportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is the report, in the requested format.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VulnerabilityReportResponse) Reset() {
	*x = VulnerabilityReportResponse{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VulnerabilityReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityReportResponse) ProtoMessage() {}

func (x *VulnerabilityReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityReportResponse.ProtoReflect.Descriptor instead.
func (*VulnerabilityReportResponse) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{1}
}

func (x *VulnerabilityReportResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SBOMRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SchematicID is the hex-encoded SHA-256 of the schematic the SBOM covers.
	SchematicId string `protobuf:"bytes,1,opt,name=schematic_id,json=schematicId,proto3" json:"schematic_id,omitempty"`
	// TalosVersion is the Talos version the schematic was built for.
	TalosVersion string `protobuf:"bytes,2,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	// Arch is the architecture the schematic was built for.
	Arch          Arch `protobuf:"varint,3,opt,name=arch,proto3,enum=imagefactory.Arch" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBOMRequest) Reset() {
	*x = SBOMRequest{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBOMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBOMRequest) ProtoMessage() {}

func (x *SBOMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBOMRequest.ProtoReflect.Descriptor instead.
func (*SBOMRequest) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{2}
}

func (x *SBOMRequest) GetSchematicId() string {
	if x != nil {
		return x.SchematicId
	}
	return ""
}

func (x *SBOMRequest) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

func (x *SBOMRequest) GetArch() Arch {
	if x != nil {
		return x.Arch
	}
	return Arch_UNKNOWN_ARCH
}

type SBOMResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is the SPDX bundle, as JSON.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBOMResponse) Reset() {
	*x = SBOMResponse{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBOMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBOMResponse) ProtoMessage() {}

func (x *SBOMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBOMResponse.ProtoReflect.Descriptor instead.
func (*SBOMResponse) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{3}
}

func (x *SBOMResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type VEXDocumentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TalosVersion is the Talos version the document covers.
	TalosVersion  string `protobuf:"bytes,1,opt,name=talos_version,json=talosVersion,proto3" json:"talos_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VEXDocumentRequest) Reset() {
	*x = VEXDocumentRequest{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VEXDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VEXDocumentRequest) ProtoMessage() {}

func (x *VEXDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VEXDocumentRequest.ProtoReflect.Descriptor instead.
func (*VEXDocumentRequest) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{4}
}

func (x *VEXDocumentRequest) GetTalosVersion() string {
	if x != nil {
		return x.TalosVersion
	}
	return ""
}

type VEXDocumentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Data is the OpenVEX document, as JSON.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VEXDocumentResponse) Reset() {
	*x = VEXDocumentResponse{}
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VEXDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VEXDocumentResponse) ProtoMessage() {}

func (x *VEXDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_omni_imagefactory_imagefactory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VEXDocumentResponse.ProtoReflect.Descriptor instead.
func (*VEXDocumentResponse) Descriptor() ([]byte, []int) {
	return file_omni_imagefactory_imagefactory_proto_rawDescGZIP(), []int{5}
}

func (x *VEXDocumentResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_omni_imagefactory_imagefactory_proto protoreflect.FileDescriptor

const file_omni_imagefactory_imagefactory_proto_rawDesc = "" +
	"\n" +
	"$omni/imagefactory/imagefactory.proto\x12\fimagefactory\"\xcd\x01\n" +
	"\x1aVulnerabilityReportRequest\x12!\n" +
	"\fschematic_id\x18\x01 \x01(\tR\vschematicId\x12#\n" +
	"\rtalos_version\x18\x02 \x01(\tR\ftalosVersion\x12&\n" +
	"\x04arch\x18\x03 \x01(\x0e2\x12.imagefactory.ArchR\x04arch\x12?\n" +
	"\x06format\x18\x04 \x01(\x0e2'.imagefactory.VulnerabilityReportFormatR\x06format\"1\n" +
	"\x1bVulnerabilityReportResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"}\n" +
	"\vSBOMRequest\x12!\n" +
	"\fschematic_id\x18\x01 \x01(\tR\vschematicId\x12#\n" +
	"\rtalos_version\x18\x02 \x01(\tR\ftalosVersion\x12&\n" +
	"\x04arch\x18\x03 \x01(\x0e2\x12.imagefactory.ArchR\x04arch\"\"\n" +
	"\fSBOMResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"9\n" +
	"\x12VEXDocumentRequest\x12#\n" +
	"\rtalos_version\x18\x01 \x01(\tR\ftalosVersion\")\n" +
	"\x13VEXDocumentResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*.\n" +
	"\x04Arch\x12\x10\n" +
	"\fUNKNOWN_ARCH\x10\x00\x12\t\n" +
	"\x05AMD64\x10\x01\x12\t\n" +
	"\x05ARM64\x10\x02*^\n" +
	"\x19VulnerabilityReportFormat\x12\x12\n" +
	"\x0eUNKNOWN_FORMAT\x10\x00\x12\b\n" +
	"\x04JSON\x10\x01\x12\t\n" +
	"\x05SARIF\x10\x02\x12\r\n" +
	"\tCYCLONEDX\x10\x03\x12\t\n" +
	"\x05TABLE\x10\x042\x94\x02\n" +
	"\x13ImageFactoryService\x12j\n" +
	"\x13VulnerabilityReport\x12(.imagefactory.VulnerabilityReportRequest\x1a).imagefactory.VulnerabilityReportResponse\x12=\n" +
	"\x04SBOM\x12\x19.imagefactory.SBOMRequest\x1a\x1a.imagefactory.SBOMResponse\x12R\n" +
	"\vVEXDocument\x12 .imagefactory.VEXDocumentRequest\x1a!.imagefactory.VEXDocumentResponseB9Z7github.com/siderolabs/omni/client/api/omni/imagefactoryb\x06proto3"

var (
	file_omni_imagefactory_imagefactory_proto_rawDescOnce sync.Once
	file_omni_imagefactory_imagefactory_proto_rawDescData []byte
)

func file_omni_imagefactory_imagefactory_proto_rawDescGZIP() []byte {
	file_omni_imagefactory_imagefactory_proto_rawDescOnce.Do(func() {
		file_omni_imagefactory_imagefactory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_omni_imagefactory_imagefactory_proto_rawDesc), len(file_omni_imagefactory_imagefactory_proto_rawDesc)))
	})
	return file_omni_imagefactory_imagefactory_proto_rawDescData
}

var file_omni_imagefactory_imagefactory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_omni_imagefactory_imagefactory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_omni_imagefactory_imagefactory_proto_goTypes = []any{
	(Arch)(0),                           // 0: imagefactory.Arch
	(VulnerabilityReportFormat)(0),      // 1: imagefactory.VulnerabilityReportFormat
	(*VulnerabilityReportRequest)(nil),  // 2: imagefactory.VulnerabilityReportRequest
	(*VulnerabilityReportResponse)(nil), // 3: imagefactory.VulnerabilityReportResponse
	(*SBOMRequest)(nil),                 // 4: imagefactory.SBOMRequest
	(*SBOMResponse)(nil),                // 5: imagefactory.SBOMResponse
	(*VEXDocumentRequest)(nil),          // 6: imagefactory.VEXDocumentRequest
	(*VEXDocumentResponse)(nil),         // 7: imagefactory.VEXDocumentResponse
}
var file_omni_imagefactory_imagefactory_proto_depIdxs = []int32{
	0, // 0: imagefactory.VulnerabilityReportRequest.arch:type_name -> imagefactory.Arch
	1, // 1: imagefactory.VulnerabilityReportRequest.format:type_name -> imagefactory.VulnerabilityReportFormat
	0, // 2: imagefactory.SBOMRequest.arch:type_name -> imagefactory.Arch
	2, // 3: imagefactory.ImageFactoryService.VulnerabilityReport:input_type -> imagefactory.VulnerabilityReportRequest
	4, // 4: imagefactory.ImageFactoryService.SBOM:input_type -> imagefactory.SBOMRequest
	6, // 5: imagefactory.ImageFactoryService.VEXDocument:input_type -> imagefactory.VEXDocumentRequest
	3, // 6: imagefactory.ImageFactoryService.VulnerabilityReport:output_type -> imagefactory.VulnerabilityReportResponse
	5, // 7: imagefactory.ImageFactoryService.SBOM:output_type -> imagefactory.SBOMResponse
	7, // 8: imagefactory.ImageFactoryService.VEXDocument:output_type -> imagefactory.VEXDocumentResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_omni_imagefactory_imagefactory_proto_init() }
func file_omni_imagefactory_imagefactory_proto_init() {
	if File_omni_imagefactory_imagefactory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_omni_imagefactory_imagefactory_proto_rawDesc), len(file_omni_imagefactory_imagefactory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_omni_imagefactory_imagefactory_proto_goTypes,
		DependencyIndexes: file_omni_imagefactory_imagefactory_proto_depIdxs,
		EnumInfos:         file_omni_imagefactory_imagefactory_proto_enumTypes,
		MessageInfos:      file_omni_imagefactory_imagefactory_proto_msgTypes,
	}.Build()
	File_omni_imagefactory_imagefactory_proto = out.File
	file_omni_imagefactory_imagefactory_proto_goTypes = nil
	file_omni_imagefactory_imagefactory_proto_depIdxs = nil
}
