// Copyright (c) 2026 Sidero Labs, Inc.
//
// Use of this software is governed by the Business Source License
// included in the LICENSE file.
import { defineAsyncComponent } from 'vue'

export const icons = {
  'arrow-down-tray': defineAsyncComponent(() => import('../icons/IconArrowDownTray.vue')),
  'action-horizontal': defineAsyncComponent(() => import('../icons/IconActionHorizontal.vue')),
  'action-horizontal-animated': defineAsyncComponent(
    () => import('../icons/IconActionHorizontalAnimated.vue'),
  ),
  'arrow-path': defineAsyncComponent(() => import('../icons/IconArrowPath.vue')),
  'arrow-path-circle': defineAsyncComponent(() => import('../icons/IconArrowPathCircle.vue')),
  'arrow-right-square': defineAsyncComponent(() => import('../icons/IconArrowRightSquare.vue')),
  'arrow-up-on-square-stack': defineAsyncComponent(
    () => import('../icons/IconArrowUpOnSquareStack.vue'),
  ),
  'arrows-right-left': defineAsyncComponent(() => import('../icons/IconArrowsRightLeft.vue')),
  'document-text': defineAsyncComponent(() => import('../icons/IconDocumentText.vue')),
  box: defineAsyncComponent(() => import('../icons/IconBox.vue')),
  calendar: defineAsyncComponent(() => import('../icons/IconCalendar.vue')),
  'chart-bar': defineAsyncComponent(() => import('../icons/IconChartBar.vue')),
  check: defineAsyncComponent(() => import('../icons/IconCheck.vue')),
  'check-circle': defineAsyncComponent(() => import('../icons/IconCheckCircle.vue')),
  'check-circle-solid': defineAsyncComponent(() => import('../icons/IconCheckCircleSolid.vue')),
  'chevron-double-left': defineAsyncComponent(() => import('../icons/IconChevronDoubleLeft.vue')),
  'chevron-double-right': defineAsyncComponent(() => import('../icons/IconChevronDoubleRight.vue')),
  'chevron-down': defineAsyncComponent(() => import('../icons/IconChevronDown.vue')),
  'chevron-left': defineAsyncComponent(() => import('../icons/IconChevronLeft.vue')),
  'chevron-right': defineAsyncComponent(() => import('../icons/IconChevronRight.vue')),
  'chevron-up': defineAsyncComponent(() => import('../icons/IconChevronUp.vue')),
  'circle-stack': defineAsyncComponent(() => import('../icons/IconCircleStack.vue')),
  close: defineAsyncComponent(() => import('../icons/IconClose.vue')),
  'cloud-connection': defineAsyncComponent(() => import('../icons/IconCloudConnection.vue')),
  clusters: defineAsyncComponent(() => import('../icons/IconClusters.vue')),
  'code-bracket': defineAsyncComponent(() => import('../icons/IconCodeBracket.vue')),
  'computer-desktop': defineAsyncComponent(() => import('../icons/IconComputerDesktop.vue')),
  copy: defineAsyncComponent(() => import('../icons/IconCopy.vue')),
  'cpu-chip': defineAsyncComponent(() => import('../icons/IconCpuChip.vue')),
  dashboard: defineAsyncComponent(() => import('../icons/IconDashboard.vue')),
  delete: defineAsyncComponent(() => import('../icons/IconDelete.vue')),
  document: defineAsyncComponent(() => import('../icons/IconDocument.vue')),
  documentation: defineAsyncComponent(() => import('../icons/IconDocumentation.vue')),
  dot: defineAsyncComponent(() => import('../icons/IconDot.vue')),
  'drop-up': defineAsyncComponent(() => import('../icons/IconDropUp.vue')),
  dropdown: defineAsyncComponent(() => import('../icons/IconDropdown.vue')),
  edit: defineAsyncComponent(() => import('../icons/IconEdit.vue')),
  eye: defineAsyncComponent(() => import('../icons/IconEye.vue')),
  exclamation: defineAsyncComponent(() => import('../icons/IconExclamationClear.vue')),
  'exclamation-circle': defineAsyncComponent(() => import('../icons/IconExclamationCircle.vue')),
  'exclamation-triangle': defineAsyncComponent(
    () => import('../icons/IconExclamationTriangle.vue'),
  ),
  'exclamation-triangle-solid': defineAsyncComponent(
    () => import('../icons/IconExclamationTriangleSolid.vue'),
  ),
  window: defineAsyncComponent(() => import('../icons/IconWindow.vue')),
  'extensions-toggle': defineAsyncComponent(() => import('../icons/IconExtensionsToggle.vue')),
  extensions: defineAsyncComponent(() => import('../icons/IconExtensions.vue')),
  'external-link': defineAsyncComponent(() => import('../icons/IconExternalLink.vue')),
  fullscreen: defineAsyncComponent(() => import('../icons/IconFullscreen.vue')),
  hamburger: defineAsyncComponent(() => import('../icons/IconHamburger.vue')),
  home: defineAsyncComponent(() => import('../icons/IconHome.vue')),
  info: defineAsyncComponent(() => import('../icons/IconInfo.vue')),
  key: defineAsyncComponent(() => import('../icons/IconKey.vue')),
  'kube-config': defineAsyncComponent(() => import('../icons/IconKubeConfig.vue')),
  kubernetes: defineAsyncComponent(() => import('../icons/IconKubernetes.vue')),
  lifebuoy: defineAsyncComponent(() => import('../icons/IconLifebuoy.vue')),
  'list-bullet': defineAsyncComponent(() => import('../icons/IconListBullet.vue')),
  loading: defineAsyncComponent(() => import('../icons/IconLoading.vue')),
  'locked-toggle': defineAsyncComponent(() => import('../icons/IconLockClosedToggle.vue')),
  locked: defineAsyncComponent(() => import('../icons/IconLocked.vue')),
  log: defineAsyncComponent(() => import('../icons/IconLog.vue')),
  logo: defineAsyncComponent(() => import('../icons/IconLogo.vue')),
  'long-arrow-down': defineAsyncComponent(() => import('../icons/IconLongArrowDown.vue')),
  'long-arrow-top': defineAsyncComponent(() => import('../icons/IconLongArrowTop.vue')),
  'machines-autoprovisioned': defineAsyncComponent(
    () => import('../icons/IconMachinesAutoprovisioned.vue'),
  ),
  'machines-manual': defineAsyncComponent(() => import('../icons/IconMachinesManual.vue')),
  minus: defineAsyncComponent(() => import('../icons/IconMinus.vue')),
  'minus-circle-solid': defineAsyncComponent(() => import('../icons/IconMinusCircleSolid.vue')),
  moon: defineAsyncComponent(() => import('../icons/IconMoon.vue')),
  'moon-solid': defineAsyncComponent(() => import('../icons/IconMoonSolid.vue')),
  'no-connection': defineAsyncComponent(() => import('../icons/IconNoConnection.vue')),
  'no-symbol': defineAsyncComponent(() => import('../icons/IconNoSymbol.vue')),
  nodes: defineAsyncComponent(() => import('../icons/IconNodes.vue')),
  overview: defineAsyncComponent(() => import('../icons/IconOverview.vue')),
  'pause-circle': defineAsyncComponent(() => import('../icons/IconPauseCircle.vue')),
  'play-circle': defineAsyncComponent(() => import('../icons/IconPlayCircle.vue')),
  plus: defineAsyncComponent(() => import('../icons/IconPlus.vue')),
  pods: defineAsyncComponent(() => import('../icons/IconPods.vue')),
  power: defineAsyncComponent(() => import('../icons/IconPower.vue')),
  'question-mark-circle': defineAsyncComponent(() => import('../icons/IconQuestionMarkCircle.vue')),
  'question-mark-circle-solid': defineAsyncComponent(
    () => import('../icons/IconQuestionMarkCircleSolid.vue'),
  ),
  reset: defineAsyncComponent(() => import('../icons/IconReset.vue')),
  rollback: defineAsyncComponent(() => import('../icons/IconRollback.vue')),
  search: defineAsyncComponent(() => import('../icons/IconSearch.vue')),
  'server-network': defineAsyncComponent(() => import('../icons/IconServerNetwork.vue')),
  'server-stack': defineAsyncComponent(() => import('../icons/IconServerStack.vue')),
  server: defineAsyncComponent(() => import('../icons/IconServer.vue')),
  'settings-toggle': defineAsyncComponent(() => import('../icons/IconSettingsToggle.vue')),
  settings: defineAsyncComponent(() => import('../icons/IconSettings.vue')),
  'sidero-monochrome': defineAsyncComponent(() => import('../icons/IconSideroMonochrome.vue')),
  stop: defineAsyncComponent(() => import('../icons/IconStop.vue')),
  sun: defineAsyncComponent(() => import('../icons/IconSun.vue')),
  tag: defineAsyncComponent(() => import('../icons/IconTag.vue')),
  talos: defineAsyncComponent(() => import('../icons/IconTalos.vue')),
  'talos-config': defineAsyncComponent(() => import('../icons/IconTalosConfig.vue')),
  time: defineAsyncComponent(() => import('../icons/IconTime.vue')),
  unlocked: defineAsyncComponent(() => import('../icons/IconUnlocked.vue')),
  'upgrade-available': defineAsyncComponent(() => import('../icons/IconUpgradeAvailable.vue')),
  upgrade: defineAsyncComponent(() => import('../icons/IconUpgrade.vue')),
  'user-plus': defineAsyncComponent(() => import('../icons/IconUserPlus.vue')),
  users: defineAsyncComponent(() => import('../icons/IconUsers.vue')),
  'x-circle': defineAsyncComponent(() => import('../icons/IconXCircle.vue')),
  'x-circle-solid': defineAsyncComponent(() => import('../icons/IconXCircleSolid.vue')),
}
